### ISSUE TITLE
ventoy

### ISSUE THREAD

**Issue by Honza572** [obhq/obliteration#1059]
Hi, sorry for typing it here but I can't find a way on mobile to message you: can you please send me here the link for ventoy discord server? (This is for VocalFan, sorry but I'm completely lost on mobile github)

**Comment by ultimaweapon** [comment]
What is ventoy discord server?

**Comment by VocalFan** [comment]
> Hi, sorry for typing it here but I can't find a way on mobile to message you: can you please send me here the link for ventoy discord server? (This is for VocalFan, sorry but I'm completely lost on mobile github)

Uh... I don't think that exists? For like... Multiple years atleast.
