### ISSUE TITLE
Rename QC workflow to Pre-build

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#107]
It just look weird to have `QC / Quality Checks` like:

```
PR Build / QC / Quality Checks (pull_request)
PR Build / Build / Windows (pull_request)
PR Build / Build / Linux (pull_request)
PR Build / Build / Mac (pull_request)
```

VS:

```
PR Build / Pre-build / Quality Checks (pull_request)
PR Build / Build / Windows (pull_request)
PR Build / Build / Linux (pull_request)
PR Build / Build / Mac (pull_request)
```

We can also add other steps that does not related to QC in the future because it not only for QC anymore.

**Comment by Mou-Ikkai** [comment]
Perhaps the QC file will be a general checking file
It just will have multiple jobs in the file for different checks.

**Comment by ultimaweapon** [comment]
Yes that is the idea.
