### ISSUE TITLE
(Cooperation improvement) Create a repository for the website source code

### ISSUE THREAD

**Issue by hardBSDk** [obhq/obliteration#1089]
It will allow better cooperation and reduce the maintenance effort.

**Comment by ultimaweapon** [comment]
Do you mean the source of https://obliteration.net? If yes we already have it https://github.com/obhq/obhq.github.io.

**Comment by hardBSDk** [comment]
@ultimaweapon Yes, thanks.

This repository is not pinned on the organization.

**Comment by ultimaweapon** [comment]
Pinned. Thanks for letting us know.
