### ISSUE TITLE
Create CNAME record for dev.obliteration.net

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#1101]
@VocalFan can you create a `CNAME` record for `dev.obliteration.net` with `obhq.github.io` as a value?

**Comment by VocalFan** [comment]
Yup yup

**Comment by VocalFan** [comment]
So, I feel like this is a lil redundant as I already have

```
*.obliteration.net is an alias of obliteration.net.
```

And 

```
obliteration.net is an alias of obhq.github.io.
```

**Comment by ultimaweapon** [comment]
We should not use wildcard here due to it is possible for domain takeovers as stated [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site).

> This rule was basically made so that [www.obliteration.net](http://www.obliteration.net) also worked instead of just obliteration.net

There is an instruction on the above link to make it work on both www and non-www. But let's fix the wildcard issue first.

**Comment by VocalFan** [comment]
```
CNAME(Proxied | auto TTL)

dev.obliteration.net is an alias of obhq.github.io.

CNAME(Proxied | auto TTL)

www.obliteration.net is an alias of obliteration.net.
```

**Comment by VocalFan** [comment]
There x3

**Comment by ultimaweapon** [comment]
Thanks.

**Comment by ultimaweapon** [comment]
Should working by now but it is not. Can you disable the CloudFlare proxy?

**Comment by VocalFan** [comment]
I don't think it's me pal

**Comment by VocalFan** [comment]
I mean, because it IS directing to github.

**Comment by ultimaweapon** [comment]
GitHub required the record to be `CNAME` but what we got from CloudFlare is `A` because it is proxied.

**Comment by VocalFan** [comment]
Disabled Proxied mode, seems to work

**Comment by ultimaweapon** [comment]
Thanks. It works on my side now although there is a problem with SSL but that is another issue so I'll close this.
