### ISSUE TITLE
PS4UPDATE.PUP from Sony's Website

### ISSUE THREAD

**Issue by nesper8** [obhq/obliteration#112]
Sony now has put update and re-installation .PUP files here now on this site https://www.playstation.com/en-us/support/hardware/ps4/system-software/
Is it possible to install updates from these files provided by Sony? (ofc after decrypting them)

**Comment by ultimaweapon** [comment]
Yes, after it was decrypted by https://github.com/ultimaweapon/ps4-update-decryptor or https://github.com/idc/ps4-pup_decrypt.

**Comment by nesper8** [comment]
Which one to be exact?
The update .PUP or the restore .PUP?
Also would be cool to add this info on the README

**Comment by ultimaweapon** [comment]
Either one that give you `PS4UPDATE1.PUP.dec` once decrypted. Yes it will be good if we have the instructions for this in README. We already have an issue for [this](https://github.com/obhq/obliteration/issues/20).

**Comment by nesper8** [comment]
Thank you for the clarification 
I'll close this issue now
