### ISSUE TITLE
Output appimages on CI

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#123]
AppImages are usually easier to use than Flatpaks. (Just double-click to run!)

They also include all of the dependencies and are usually smaller than flatpaks or snaps. All the user would have to do to use Obliteration on linux would be to download the AppImage, and double click.

**Comment by ultimaweapon** [comment]
Seems like it is not officially available on some distros (e.g. Arch). So we should provide AppImage as additional instead of removing Flatpak.

**Comment by VocalFan** [comment]
> Seems like it is not officially available on some distros (e.g. Arch). So we should provide AppImage as additional instead of removing Flatpak.

How about...

We make Flatpaks for Flathub hosting.
We make AppImages for portable / local downloads. Plus they're less of a commitment for people wanting to quickly test, download and run! Instead of like how for Flatpaks you need to download and install dependencies, then install the app.

**Comment by ultimaweapon** [comment]
We can publish to Flathub for the stable release. For development build we should not publish to Flathub and provide only bundle files and AppImage on CI.

**Comment by yisonPylkita** [comment]
Just to chip in: in the past I've made a few AppImages of Qt5 apps with https://github.com/probonopd/linuxdeployqt for both Linux and ChromeOS. I used qmake instead of CMake though, yet documentation says CMake is supported too. 

AppImage should work just fine on any distro. Internally it's just an archive that mounts itself via fuse2 to its own fs mount point with every dependency included except GLibC.

**Comment by ultimaweapon** [comment]
Interesting. Let's try adding AppImage and see how it works. If no any issues we can remove Flatpak.

**Comment by yisonPylkita** [comment]
Great. @VocalFan can I take this one?

**Comment by VocalFan** [comment]
> Great. @VocalFan can I take this one?

If you were waiting for confirmation... Yes. Unless if I say I'll do it... Anyone else can! :3

**Comment by yisonPylkita** [comment]
I started work already but `linuxdeployqt` supports only Qt5. https://github.com/linuxdeploy/linuxdeploy looks promising though

**Comment by VocalFan** [comment]
So, this is really dead.

**Comment by ultimaweapon** [comment]
Now our binary don't need fancy dependencies so it can run directly without Flatpak or AppImage. See #1140 for the PR that switched to this.
