### ISSUE TITLE
Change branch name for Flatpak on Development Build

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#124]
Right now it is `master`. We already supplied `--default-branch dev` when building but it does not work somehow.

**Comment by VocalFan** [comment]
Uh... Because the "master" branch on github has been remamed to the "main" branch?

**Comment by ultimaweapon** [comment]
It is not related to the Git branch.

**Comment by ultimaweapon** [comment]
No more Flatpak because disk space on GitHub Actions not large enough to build it.
