### ISSUE TITLE
Replace Recompiler with x86_64 emulation via Unicorn Engine

### ISSUE THREAD

**Issue by bayedieng** [obhq/obliteration#133]
As recompilation takes significant effort due to sheer amount of x86 [instructions](https://fgiesen.wordpress.com/2016/08/25/how-many-x86-instructions-are-there/), we've decided to shift our efforts CPU emulation using the Unicorn Engine framework. This would be a significant change in the codebase which would allow us to more  easily pursue pertinent tasks in regards to supporting ps4 games (e.g. graphics, sound, etc...).

**Comment by ultimaweapon** [comment]
After we was trying on Unicorn we decided not to go this route and we are going to use https://github.com/bytecodealliance/wasmtime/tree/main/cranelift instead. The reasons are:

- Unicorn separated the emulated code from the application code, which make it hard to communication between the code that we run in the Unicorn and our application.
- With the previous reason we need some effort to be able to use it (e.g. implementing a new memory allocator) and if the outcome is not good that mean our effort is losing for nothing.
- From what we saw on the internet the performance of running x86-64 code with QEMU on AArch64 is not good.
