### ISSUE TITLE
Parsing kernel debug arguments manually

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#16]
Right now we use `serde_yaml` which is quite overkill. So it is better to parse it manually because the file structure that we are using is very simple.

**Comment by Mou-Ikkai** [comment]
Issues with latest PR: Drive paths don't work (D:\path\)
Newlines at end of file break parser.

**Comment by bayedieng** [comment]
Could you show  ```.kernel-debug``` file so I can see?

**Comment by ultimaweapon** [comment]
Now we have used `serde_yaml` for keeping file metedata so we have no reason to do this anymore.
