### ISSUE TITLE
Setup wizard is broken on high-dpi screen

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#190]
![Untitled](https://user-images.githubusercontent.com/3048307/232232259-0cf43497-0f57-405b-8d2a-ed15fa6a97bc.png)

**Comment by VocalFan** [comment]
@ultimaweapon Retest since our changing of the Wizard.

**Comment by VocalFan** [comment]
![image](https://github.com/obhq/obliteration/assets/45863583/553e2542-ca62-4140-9bd3-2953090272f6)
![image](https://github.com/obhq/obliteration/assets/45863583/cd91053e-60af-4dc6-8e10-e6f64200153d)
Tested myself at 150%, fixed.
