### ISSUE TITLE
Add Dark Mode.

### ISSUE THREAD

**Issue by Mou-Ikkai** [obhq/obliteration#22]
We could make a setting for it, OR, we can have it obey the user's settings on Windows.

```C++
    QSettings settings("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",QSettings::NativeFormat);
    if(settings.value("AppsUseLightTheme")==0){
    }
 ```

**Comment by ultimaweapon** [comment]
My idea is we have a setting for this using the same dialog as #2. The available choices for this settings are:

1. Same as system
2. Light
3. Dark

`Same as system` will be default value. With this way it will follow system theme if user does not explicitly set this setting, which should be the behavior that expected by user.

**Comment by ultimaweapon** [comment]
@bayedieng I saw your screenshot using a dark theme. How?

**Comment by bayedieng** [comment]
I have dark mode set on my Pop OS system it does it globally, I think. So does macOS.

**Comment by ultimaweapon** [comment]
I guess Pop!_OS install a custom theme for Qt. Could you check what is the name for its Qt dark theme?

**Comment by bayedieng** [comment]
I'm not sure how to find it. I'm guessing it's some env variable that Qt preinstalls

**Comment by ultimaweapon** [comment]
Okay no problem. I also have no idea too. Will try Pop!_OS later to figure out.

**Comment by bayedieng** [comment]
If you have ubuntu 22.04 it should likely have as the same behavior as Pop OS is ubuntu-based.

**Comment by ultimaweapon** [comment]
Just notice Qt is officially working on this https://bugreports.qt.io/browse/QTBUG-72028. After discussion we will provide in interim solution for this until Qt is official supported.
