### ISSUE TITLE
Try Slint as a new GUI

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#238]
Now they just released a new version with a new license that is compatible with MIT license. So it is a good opportunity to try it to see if we can get rid of C++.

The new GUI should be placed in `src/gui` while we are experimenting with it. It should not ship with the release to the end users until it comes out from experimental.

**Comment by VocalFan** [comment]
Plus, I think Slint looks pretty nice, especially with the Material style.

**Comment by bayedieng** [comment]
Slint does indeed seem like a really good fit, if this were to be implemented would it not be more suitable for the kernel to change to a library instead of a binary?

**Comment by ultimaweapon** [comment]
It is quite hard to free all of the resources when the game is stopped if we make the kernel as a library compared to killing the process and let the OS handle that.

**Comment by SuchAFuriousDeath** [comment]
Current progress: 
<img width="961" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/91beb911-fb54-4561-93bb-95b358fcf71e">

**Comment by SuchAFuriousDeath** [comment]
Progress report: 
<img width="1534" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/7b33dd54-d828-4453-96e8-2cb7b51f365e">

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon I'll have to change the UI around slightly, it seems that Slint doesn't support multiple popup windows at the same time (And the issue is that I don't know of a way to create the two dropdown menus without popups)
