### ISSUE TITLE
Unimplemented syscalls - 340

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [obhq/obliteration#250]
`syscall 340 at 0x0000000000002a7a on /system/common/lib/libkernel.sprx', kernel\src\syscalls\mod.rs:47:18`

**Comment by VocalFan** [comment]
Syscall 340, also known as [sigprocmask](https://man.freebsd.org/cgi/man.cgi?query=sigprocmask&sektion=2&n=1), manipulates or observes the current signal mask. The source code is here: https://cgit.freebsd.org/src/tree/sys/kern/kern_sig.c#n1130
