### ISSUE TITLE
Syscall 599: Relocation type 6 is not supported

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#253]
This error happens on both Amplitude and Project Diva X.

Amplitude log: [amplog.txt](https://github.com/obhq/obliteration/files/12043800/amplog.txt)
Project Diva X: [PDXlog.txt](https://github.com/obhq/obliteration/files/12043801/PDXlog.txt)

**Comment by VocalFan** [comment]
@ultimaweapon So, with some very simple testing, seems like it's just another one that can be `{continue;}`'d

Also, how tf do you get the function names-

`/// See reloc_non_plt on the PS4 kernel for a reference.`

**Comment by ultimaweapon** [comment]
You don't see its effect immediately that means putting continue seems like to work but it may not.

For the function name, if it is the official name from Sony you can find from the string list that is a logging message. Some logging messages will have a function name in it.

**Comment by VocalFan** [comment]
Tom Clancy The Division also requires Relocation type 6 as well.

**Comment by VocalFan** [comment]
^ We Are Doomed seems to also use this Relocation type.

**Comment by ultimaweapon** [comment]
Verify if there are any different with the PS4 kernel.

**Comment by VocalFan** [comment]
...Nah :P

Because once again, idfk how to.

**Comment by VocalFan** [comment]
You seem to mention this Relocation type in module/module.rs, but never define it elsewhere, like rtld, or the Relocation Type number it uses.

**Comment by ultimaweapon** [comment]
The `module/module.rs` is an old version before I saw the PS4 kernel while the `rtld` is a new version based on the PS4. We will eventually remove `module` when the `rtld` is completed.

**Comment by VocalFan** [comment]
Still, seems this Reloc is kinda important as a good half of my games use it...

**Comment by ultimaweapon** [comment]
I'll be working on this soon because it is required after the syscall 608 is finished.

**Comment by ultimaweapon** [comment]
Actually syscall 608 already finished but I did not commit the last part because the crash is awaiting ahead.

**Comment by VocalFan** [comment]
> Actually syscall 608 already finished but I did not commit the last part because the crash is awaiting ahead.

Soon, I'll finally be able to end my "Part # of Syscall 608, woo!" counter in the Discord server. Lol.

**Comment by VocalFan** [comment]
![Screenshot_20230810-120120.png](https://github.com/obhq/obliteration/assets/45863583/ac1c8dd3-d228-4f7d-8f45-f7e8d8ebf731)

I mean it, haha.

**Comment by VocalFan** [comment]
Mighty No. 9 also uses this relocation type.

Current list: 
Amplitude
Hatsune Miku: Project Diva X
Mighty No. 9
The Division 2
We are Doomed

About 2/3rd of my extracted games use this relocation type.

**Comment by ultimaweapon** [comment]
Thanks for testing. This one is depend on #300.

**Comment by VocalFan** [comment]
> Thanks for testing. This one is depend on #300.

Oh, another thing, some of my games have the SDK version error you added, want me to make an issue listing them?

**Comment by ultimaweapon** [comment]
Yep, please create a dedicated issue for it.
