### ISSUE TITLE
Dumps of Disc games always crash the kernel.

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#254]
It seems like Window's Data Execution Prevention doesn't like how Obliteration handles Disc based games, or perhaps another underlying cause. 

In the GUI, it'll just exit with the textbox: `The Kernel Crashed`

In the kernel, VSCode returns the exception: `Exception 0xc0000005 encountered at address 0x1a0fa42907d: User-mode data execution prevention (DEP) violation at location 0x1a0fa42907d`

[Persona5Rlog.txt](https://github.com/obhq/obliteration/files/12043851/Persona5Rlog.txt)

```
; Symbol: no symbol info
; Source: unknown
1A0FA42907D: 41 5B                      pop    r11
^ Exception 0xc0000005 encountered at address 0x1a0fa42907d: User-mode data execution prevention (DEP) violation at location 0x1a0fa42907d
1A0FA42907F: 5A                         pop    rdx
1A0FA429080: 48 85 C0                   test   rax, rax
1A0FA429083: 75 0A                      jne    0x1a0fa42908f
1A0FA429085: 48 8B 43 50                mov    rax, qword ptr [rbx + 0x50]
1A0FA429089: 48 8B 53 58                mov    rdx, qword ptr [rbx + 0x58]
1A0FA42908D: EB 04                      jmp    0x1a0fa429093
1A0FA42908F: 49 83 CB 01                or     r11, 0x1
1A0FA429093: 41 5C                      pop    r12
1A0FA429095: 5B                         pop    rbx
1A0FA429096: 5E                         pop    rsi
1A0FA429097: 5F                         pop    rdi
1A0FA429098: 48 B9 9C 1D 39 FA A0 01 >  movabs rcx, 0x1a0fa391d9c
1A0FA4290A2: 4D 31 C0                   xor    r8, r8
1A0FA4290A5: 4D 31 C9                   xor    r9, r9
1A0FA4290A8: 4D 31 D2                   xor    r10, r10
1A0FA4290AB: 45 89 DB                   mov    r11d, r11d
1A0FA4290AE: 41 53                      push   r11
1A0FA4290B0: 9D                         popfq  
1A0FA4290B1: C9                         leave  
1A0FA4290B2: E9 E5 8C F6 FF             jmp    0x1a0fa391d9c
1A0FA4290B7: 00 00                      add    byte ptr [rax], al
1A0FA4290B9: 00 00                      add    byte ptr [rax], al
1A0FA4290BB: 00 00                      add    byte ptr [rax], al
1A0FA4290BD: 00 00                      add    byte ptr [rax], al
1A0FA4290BF: 00 55 48                   add    byte ptr [rbp + 0x48], dl
1A0FA4290C2: 89 E5                      mov    ebp, esp
1A0FA4290C4: F8                         clc    
1A0FA4290C5: 9C                         pushfq 
1A0FA4290C6: 41 5B                      pop    r11
1A0FA4290C8: 48 83 E4 F0                and    rsp, -0x10
1A0FA4290CC: 48 83 EC 60                sub    rsp, 0x60
1A0FA4290D0: 48 89 E0                   mov    rax, rsp
```

**Comment by ultimaweapon** [comment]
Strange. It should not make any different with the current version because the execution is not reached the game code yet.

**Comment by VocalFan** [comment]
Apparently, it's handled in some unsafe way if Windows is preventing it.

**Comment by VocalFan** [comment]
> Strange. It should not make any different with the current version because the execution is not reached the game code yet.

And seeing as I just upgraded my CPU from a 2700X to a 3700X on my 2nd computer, I went to test and... Yeah, same error.

**Comment by gandalfthewhite19890404** [comment]
Weird, I tried Sonic Mania - i've got only missing syscall 340, same thing with some applications like file manager.
Maybe - game depending thing?

**Comment by VocalFan** [comment]
> Weird, I tried Sonic Mania - i've got only missing syscall 340, same thing with some applications like file manager. Maybe - game depending thing?

Is that a disc dump or a PKG dump?

**Comment by gandalfthewhite19890404** [comment]
> Is that a disc dump or a PKG dump?

PKG, i've got what you're mean.
If I dump game I will have folder with all files. But then I will create PKG. And what will happen if I unpack PKG to folders again - it will be PKG DUMP?

**Comment by VocalFan** [comment]
Still happening on new logger

**Comment by VocalFan** [comment]
Seeing as my new method worked for Tom Clancy The Division...

![image](https://github.com/obhq/obliteration/assets/45863583/4f8c8088-498a-43d3-b953-8035490ea449)

I'm going to try dumping P5R with the same method I applied to The Division. @ultimaweapon If this works, I'll close the issue and chalk it up to a bad dump.
