### ISSUE TITLE
Update setup wiziard to show the instruction how to use the previous installed firmware

### ISSUE THREAD

**Issue by Danik2343** [obhq/obliteration#259]
I have a firmware that I got with a hacked PS4 for a long time, but now this PS4 is not there, please add this function.

**Comment by AlexsanderDamaceno** [comment]
As I would like to contribute to this project, I will try to solve this one.

**Comment by VocalFan** [comment]
> As I would like to contribute to this project, I will try to solve this one.

But it... Already has a solution? After you select your system folder on the Wizard... You drag and drop these 3 folders. 
![image](https://github.com/obhq/obliteration/assets/45863583/e9b4428b-3ccc-490b-aff8-bc313a0efb20)

**Comment by AlexsanderDamaceno** [comment]
I think that  Dani

> > As I would like to contribute to this project, I will try to solve this one.
> 
> But it... Already has a solution? After you select your system folder on the Wizard... You drag and drop these 3 folders. ![image](https://user-images.githubusercontent.com/45863583/254469912-e9b4428b-3ccc-490b-aff8-bc313a0efb20.png)


this includes firmware?

**Comment by AlexsanderDamaceno** [comment]
from what I know is that you need a ps4 to extract the firmware or you cant pass the wirzard part in other case

**Comment by VocalFan** [comment]
Err, no, you just close the wizard, put the folders into the System folder you selected earlier, and tada.

**Comment by VocalFan** [comment]
Unless if we got some check that doesn't- @ultimaweapon How... Do we check if the System folder the user selects actually contains firmware?

**Comment by ultimaweapon** [comment]
You only need the `system` folder from the PS4.  Then choose the folder that contains this folder for the system location on the wizard. It should not ask for the PS4 if your `system` is copied correctly from the PS4.

**Comment by ultimaweapon** [comment]
Wait, in order for the `system` folder to be usable all of the `sprx` files must be decrypted. That means if that folder was copied without SELF decryption it cannot be used.

**Comment by ultimaweapon** [comment]
Maybe we should adding a note in the system location page to tell the user that they can choose the location where the firmware was manually extracted.

**Comment by VocalFan** [comment]
@Danik2343 @AlexsanderDamaceno Will this new page work? https://github.com/obhq/obliteration/wiki/Firmware-Setup-Guide#firmware-setup-via-local-files

**Comment by Danik2343** [comment]
@VocalFan Sorry for long waiting, not working page.

**Comment by VocalFan** [comment]
Yeah we're uh, in the middle of converting it to be part of the website

**Comment by Danik2343** [comment]
@VocalFan If you still have the text, can you quote here what was written in that topic?

**Comment by ultimaweapon** [comment]
Recently we have changed how Obliteration works so the previously dumped firmware is no longer usable. Right now the tool to dump a new firmware is currently under development so you need to wait for this tool.

**Comment by VocalFan** [comment]
> Recently we have changed how Obliteration works so the previously dumped firmware is no longer usable. Right now the tool to dump a new firmware is currently under development so you need to wait for this tool.

Right now I just use a blank file called no.obf lmao

**Comment by ultimaweapon** [comment]
Fixed by #1160.
