### ISSUE TITLE
Sort games by alphabetical order

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#284]
![image](https://github.com/obhq/obliteration/assets/45863583/c320ce17-11c1-49cd-9b3b-3a858f3bc5e3)

I noticed that after installing Tom Clancy The Division, it seems to be the beginning of the list despite starting with a letter T... Could be assumed that the Trademark symbol at the end is interfering?

**Comment by ultimaweapon** [comment]
We did not do sorting yet.

**Comment by VocalFan** [comment]
...So my NPUB numbers were just conveniently all in alphabetical order? ...Huh...

**Comment by VocalFan** [comment]
Potentially will implement alphabetical order when I get home.

**Comment by VocalFan** [comment]
> Potentially will implement alphabetical order when I get home.

Nvm, screw Qt.

**Comment by VocalFan** [comment]
Should we just tie this into #238 ? It'd be a waste to implement it in Qt just to immediately replace it.
