### ISSUE TITLE
Add ability to edit Wiki

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#294]
Hey, @ultimaweapon , I'm planning on working on the Github wiki for this project but I don't have the permissions to do so, can you grant it to us?

**Comment by ultimaweapon** [comment]
Wiki is always out of date, that is why I removed it from the repository. What kind of content do you plan to add?

**Comment by VocalFan** [comment]
Ah, just to aid users with installing their firmware, and just because it's out of date doesn't make it irrelevant.

**Comment by ultimaweapon** [comment]
Done.
