### ISSUE TITLE
Not implemented: sysctl CTL_KERN:14

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#318]
TYPE (KERN_PROC): https://github.com/freebsd/freebsd-src/blob/315ee00fa9616b0a192b6834911f98bcf5316a6b/sys/sys/sysctl.h#L975C1-L975C52

Kern_Proc types: https://github.com/freebsd/freebsd-src/blob/315ee00fa9616b0a192b6834911f98bcf5316a6b/sys/sys/sysctl.h#L1001-L1038

Is required by all games. (8/8)

**Comment by ultimaweapon** [comment]
This one is a PS4 specific.

**Comment by VocalFan** [comment]
Yeah, but just showing simple grounding.

**Comment by ultimaweapon** [comment]
The data I'm looking for is a struct starting at offset 0x380 on the `proc` structure, just in case if someone can help with this. Here is what I have so far:
![Screenshot from 2023-08-29 09-18-02](https://github.com/obhq/obliteration/assets/3048307/fbada3eb-3c02-4d1f-a9f1-ec503858ec16)

**Comment by VocalFan** [comment]
> This one is going to take time because I need to find where the return value is coming from.

Hopefully the stuff from the emails help x3

**Comment by VocalFan** [comment]
Also, just a quick unrelated thing @ultimaweapon So, https://www.psdevwiki.com/ps4/Package_Files this has example PKGs such as Youtube. Thing is, if I download it and try to extract it, Obliteration gives "Cannot decrypt EKPFS -> Decryption error". I assume it has to be a f(ake)PKG?

**Comment by ultimaweapon** [comment]
Correct. We cannot decrypt the official PKG. It need to be a PKG that was dumped from a jailbroken console with de-factory standard key.

**Comment by VocalFan** [comment]
Should totally send me a Ghidra Zip with all that custom goodness you put into reverse engineering the kernel x3

**Comment by VocalFan** [comment]
![image](https://github.com/obhq/obliteration/assets/45863583/06e2e65e-0f8b-4889-918a-1389f7110410)
I meant more of a right click, export, and save as Ghidra Zip File

**Comment by VocalFan** [comment]
The reason is that it keeps all the metadata and custom types.

**Comment by VocalFan** [comment]
Oh, and the GPR file is empty.

**Comment by VocalFan** [comment]
I searched and yeah, Ghidra forces you to use Export for this. @ultimaweapon

**Comment by ultimaweapon** [comment]
We need an exact offset and length of each field.

**Comment by VocalFan** [comment]
Any terms for me to look for?

**Comment by ultimaweapon** [comment]
You need to find the functions that read/write that struct and figure out what the data it is written to.

**Comment by VocalFan** [comment]
Oh, for your UNK value:

```C
const char *__fastcall sub_140037000(unsigned int a1)
{
  const char *result; // rax
  if ( a1 > 0xFE04 )
  {
    if ( a1 > 0xFF00 )
    {
      switch ( a1 )
      {
        case 0xFFA0u:
          return "ET_SCE_PSPRELEXEC";
        case 0xFFA4u:
          return "ET_SCE_PPURELEXEC";
        case 0xFFFFu:
          return "ET_HIPROC";
      }
    }
    else
    {
      switch ( a1 )
      {
        case 0xFF00u:
          return "ET_LOPROC";
        case 0xFE0Cu:
          return "ET_SCE_STUBLIB (Stub library)";
        case 0xFE10u:
          return "ET_SCE_DYNEXEC (Main module - ASLR)";
        case 0xFE18u:
          return "ET_SCE_DYNAMIC (PRX)";
      }
    }
  }
  else
  {
    if ( a1 == 65028 )
      return "ET_SCE_RELEXEC (PRX)";
    if ( a1 > 3 )
    {
      switch ( a1 )
      {
        case 4u:
          return "CORE (Core file)";
        case 0xFE00u:
          return "ET_SCE_EXEC (Main module)";
        case 0xFE01u:
          return "ET_SCE_REPLAY_EXEC";
      }
    }
    else
    {
      switch ( a1 )
      {
        case 3u:
          return "DYN (Shared object file)";
        case 0u:
          return "ET_NONE";
        case 1u:
          return "REL (Relocatable file)";
        case 2u:
          return "EXEC (Executable file)";
      }
    }
  }
  if ( a1 - 65280 > 0xFF )
    result = "Unknown type";
  else
    result = "Unknown user defined";
  return result;
}
    ```

**Comment by VocalFan** [comment]
And just after that function, there's this one:

```c
const char *__fastcall sub_140037100(int a1)
{
  const char *result; // rax
  switch ( a1 )
  {
    case 0:
      result = "EM_NONE";
      break;
    case 1:
      result = "WE32100";
      break;
    case 2:
      result = "Sparc";
      break;
    case 3:
      result = "Intel 80386";
      break;
    case 4:
      result = "MC68000";
      break;
    case 5:
      result = "MC88000";
      break;
    case 6:
      result = "Intel 80486";
      break;
    case 7:
      result = "Intel 80860";
      break;
    case 8:
      result = "MIPS";
      break;
    case 9:
      result = "IBM System/370";
      break;
    case 20:
      result = "PowerPC";
      break;
    case 21:
      result = "PowerPC64";
      break;
    case 23:
      result = "PS3 SPU";
      break;
    case 40:
      result = "ARM";
      break;
    case 62:
      result = "x86-64";
      break;
    default:
      result = "Unknown machine";
      break;
  }
  return result;
}
```

**Comment by VocalFan** [comment]
Also seems like titleid uses wchar_t

`wchar_t aTitleid[8] = L"TitleID";`

**Comment by VocalFan** [comment]
So uh @ultimaweapon We were way off... https://www.psdevwiki.com/ps4/SELF_File_Format#ELF_Segment_Structure

**Comment by ultimaweapon** [comment]
Better to create a PR if you find something useful to add.

**Comment by VocalFan** [comment]
... So, Ultima.

```
typedef Elf64_Ehdr ElfHeader;
struct Elf64_Ehdr
{
  unsigned __int8 e_ident[16];
  Elf64_Half e_type;
  Elf64_Half e_machine;
  Elf64_Word e_version;
  Elf64_Addr e_entry;
  Elf64_Off e_phoff;
  Elf64_Off e_shoff;
  Elf64_Word e_flags;
  Elf64_Half e_ehsize;
  Elf64_Half e_phentsize;
  Elf64_Half e_phnum;
  Elf64_Half e_shentsize;
  Elf64_Half e_shnum;
  Elf64_Half e_shstrndx;
};
```

**Comment by VocalFan** [comment]
typedef Elf64_Sym ElfSymbol;
typedef uint32_t Elf64_Word;
typedef uint16_t Elf64_Half;
typedef uint64_t Elf64_Addr;
typedef uint64_t Elf64_Xword;
struct Elf64_Sym
{
  Elf64_Word st_name;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  Elf64_Half st_shndx;
  Elf64_Addr st_value;
  Elf64_Xword st_size;
};

**Comment by VocalFan** [comment]
I'll fill it out in Ghidra, then send you the Ghidra zip, alright?

**Comment by ultimaweapon** [comment]
I already have those things.

**Comment by VocalFan** [comment]
You say that when st_info and st_other aren't using the right data types in your version :P

**Comment by ultimaweapon** [comment]
`uchar` is just an alias to `unsigned __int8` so it is the same thing.

**Comment by VocalFan** [comment]
Yes, but... You also are missing values from Structs such as ptr for Elf64_dyn

**Comment by ultimaweapon** [comment]
That one is a union field with `d_val`, which have the same value. It have no benefit to make it as a union like in C so I just use simple field.

**Comment by VocalFan** [comment]
Sent -w-

**Comment by VocalFan** [comment]
It goes off the source code of the PS4 SDK for Unity, FW 5.50.

**Comment by ultimaweapon** [comment]
What do you mean?

**Comment by VocalFan** [comment]
Ah, the updated Structs and TypeDefs

**Comment by VocalFan** [comment]
If you didn't see... Email

**Comment by ultimaweapon** [comment]
What changes you have added? If it just a small fixes like we have discussed above it is not worth for me to discards my works to use your fixes.
