### ISSUE TITLE
Hacktoberfest 2023?

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#325]
Shall we add the Hacktoberfest tag to our project for this year's Hacktoberfest? I've been participating in it for 5 years, so I thought it'd be nice to let people contribute to our project to participate in Hacktoberfest!

**Comment by ultimaweapon** [comment]
How does it work?

**Comment by VocalFan** [comment]
Well, every October, Hacktoberfest begins! And any Github Repo with the Hacktoberfest tag can be worked on by the Hacktoberfest community! However, spammy/low-quality PRs get banned by the Hacktoberfest team. It allows projects to gain popularity while also letting the Hacktoberfest community create PRs to aid the project's development! It's hosted by DigitalOcean, if that helps haha.

Basically, every October, add Hacktoberfest, enjoy the gains haha. I'll make sure to mark any bad PRs as spam! And don't worry, if someone gets 2 PRs marked as spam, they're disqualified from Hacktoberfest :P

*A motivation for Hacktoberfest is how they give out items to people who get 4 PRs merged... I have like 5 shirts lol*

**Comment by ultimaweapon** [comment]
Looking good. So all we need to do is create a tag and let people open a PR with that tag?

**Comment by VocalFan** [comment]
So yeah, October 1st, add the tag!

**Comment by ultimaweapon** [comment]
Done.
