### ISSUE TITLE
Improvement to RLimit

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#326]
Possibility define RLIMIT_DATA in windows by using https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-globalmemorystatusex

**Comment by ultimaweapon** [comment]
Here is the problem:

> The information returned by the GlobalMemoryStatusEx function is volatile. There is no guarantee that two sequential calls to this function will return the same information.

So it does not work the same way as rlimit on *nix.

**Comment by ultimaweapon** [comment]
Now we are going to be a real kernel so rlimit does not need to be loaded from the host anymore.
