### ISSUE TITLE
Add CI to compile AArch64 binary on x86 Mac

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#339]
So we don't have a problem like #338 again in the future.

**Comment by ultimaweapon** [comment]
Looks like it is not free.

**Comment by bayedieng** [comment]
That's for the larger variant the regular runner should be free. This is quite confusing as I'm seeing more open source projects adding arm64 to CI.

**Comment by bayedieng** [comment]
You seem to be right. There are no free versions for now.

**Comment by ultimaweapon** [comment]
Now no one is working on AArch64 so I'll close this for now. Now GitHub also provides AArch64 macOS so we don't need this anymore.
