### ISSUE TITLE
Failed To launch Obliteration Kernel on ARM Mac 

### ISSUE THREAD

**Issue by bayedieng** [obhq/obliteration#340]
When attempting to open the PS Scene Game I get the following:

<img width="372" alt="Screenshot 2023-09-13 at 11 14 49 AM" src="https://github.com/obhq/obliteration/assets/58934805/e72f2796-fd69-4277-91eb-97557a0a7caa">

This is due to the obknl binary not being present in the app bundle.

**Comment by ultimaweapon** [comment]
Any idea what going wrong here?

**Comment by ultimaweapon** [comment]
Does this file exists on your machine `src/target/debug/obkrnl`?

**Comment by bayedieng** [comment]
Yes it does but i'm in release mode though not debug, it also runs successfully through the terminal.

**Comment by bayedieng** [comment]
Let me try it in debug mode.

**Comment by ultimaweapon** [comment]
Did you build with CMake? The app bundle is required to build with CMake.

**Comment by bayedieng** [comment]
yes I used the ```cmake --build build``` command to build the app.

**Comment by bayedieng** [comment]
The path to the obkrnl binary in the main_window.cpp file is also correct, but for some reason isn't included in the bundle.

**Comment by ultimaweapon** [comment]
Strange. CMake should copy the kernel binary to app bundle regardless the configuration.

**Comment by bayedieng** [comment]
Just attempted debug mode also fails.

**Comment by ultimaweapon** [comment]
Wait, I remembered now. For development build you need to run the GUI from the root of repository or from the VS Code.

**Comment by ultimaweapon** [comment]
Here is how it works. The `obkrnl` will be copied to the app bundle only with `cmake install`, which is a step for creating a deployable bundle. On the development we rely on the existence of `.obliteration-development` file in the current directory to detect the location of `obkrnl`. If `.obliteration-development` file is exists in the current directory the GUI will launch `src/target/[CONFIG]/obkrnl` instead of the one in the app bundle.

**Comment by bayedieng** [comment]
Thanks it works when I run it through vscode but not sure how i'd run through the terminal, I tried cmake install and it hasn't worked.

**Comment by ultimaweapon** [comment]
To run a GUI from a terminal make sure your current directory is the root of repository (where `.obliteration-development` is exists).

**Comment by bayedieng** [comment]
I see I tried opening up the entire bundle at once using the ```pen -n``` command but it works when I open it using the ```obliteration``` binary file directly.

**Comment by ultimaweapon** [comment]
I guess the `open -n` change the current working directory for the binary.
