### ISSUE TITLE
Unimplemented Syscall 557

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [obhq/obliteration#352]
```
++++++++++++++++++ P [00:00:00:00:073]:0x0000000000002020:kernel\src\syscalls\mod.rs:87
not yet implemented: syscall 557 at 0x0000000000001afa on /system/common/lib/libkernel.sprx
```

CUSTOM PS4 SYSCALL

Syscall ID | PS4 FW Version | Syscall name
-- | -- | --
557 | <=1.01? | sys_namedobj_create

<details>
  <summary>
    Function Code:
  </summary>
  <code>__int64 __usercall sys_namedobj_create@<rax>(__int64 a1@<rcx>, __int64 a2@<rdi>, __int64 a3@<rsi>, __int64 a4@<r8>, __int64 a5@<r9>, __int64 a6@<r12>, __int64 a7@<r13>, double a8@<xmm0>)
{
  unsigned int v8; // ebx
  int v9; // er14
  char *v10; // r12
  __int64 v11; // rcx
  __int64 v12; // r8
  __int64 v13; // r9
  char *v14; // r13
  __int64 v15; // rdx
  __int64 v16; // rcx
  __int64 v17; // r8
  __int64 v18; // r9
  unsigned int v19; // eax
  __int64 v20; // r15
  __int64 v21; // rdi
  __int64 v22; // rsi
  __int64 result; // rax
  __int64 v24; // [rsp+8h] [rbp-48h]
  __int64 v25; // [rsp+10h] [rbp-40h]
  unsigned __int64 *v26; // [rsp+18h] [rbp-38h]
  __int64 v27; // [rsp+20h] [rbp-30h]
  v8 = 22;
  if ( *(_QWORD *)a3 )
  {
    v25 = a2;
    v24 = *(_QWORD *)(*(_QWORD *)(a2 + 8) + 2568LL);
    v9 = *(_DWORD *)(a3 + 16);
    v10 = malloc(0x20uLL, (__int64)&unk_FFFFFFFF8325B410, 2, a1, a4, a5, a8, a6);
    v8 = copyinstr(*(_QWORD *)a3, v10, 0x20uLL, 0LL);
    if ( v8 )
    {
      free((unsigned __int64)v10, (__int64)&unk_FFFFFFFF8325B410, a7, a8, a3);
    }
    else
    {
      v14 = malloc(0x18uLL, (__int64)&unk_FFFFFFFF8325B410, 2, v11, v12, v13, a8, (__int64)v10);
      *(_QWORD *)v14 = v10;
      *((_QWORD *)v14 + 1) = *(_QWORD *)(a3 + 8);
      v19 = id_alloc(v24, &v26, v15, a8, v16, v17, v18);
      v20 = v19;
      if ( v19 == -1 )
      {
        free((unsigned __int64)v10, (__int64)&unk_FFFFFFFF8325B410, (__int64)v14, a8, 0xFFFFFFFFLL);
        free((unsigned __int64)v14, (__int64)&unk_FFFFFFFF8325B410, (__int64)v14, a8, v20);
        v8 = 35;
      }
      else
      {
        id_set((__int64)v26, v9 | 0x1000, (__int64)v14, (__int64)v10);
        v21 = *(_QWORD *)(__readgsqword(0) + 8);
        if ( (_BYTE)v9 == 7 )
          v22 = *((unsigned int *)v14 + 2);
        else
          v22 = (unsigned int)v20;
        trace_name_syscall_hook(v21, v22, (unsigned __int16)v9 | 0x1000u, v10);
        id_unlock(v26, (__int64)v14, a8, (__int64)v10, v20);
        *(_QWORD *)(v25 + 896) = (signed int)v20;
        v8 = 0;
      }
    }
  }
  result = _stack_chk_guard;
  if ( _stack_chk_guard == v27 )
    result = v8;
  return result;
}
</code>
</details>

**Comment by ultimaweapon** [comment]
@gandalfthewhite19890404 I would like to invite you to the organization so you can manage the issue tag. Are you okay with this?

**Comment by gandalfthewhite19890404** [comment]
> @gandalfthewhite19890404 I would like to invite you to the organization so you can manage the issue tag. Are you okay with this?

Well, i don't know labeling rules - what label I should set to one issue or another.
unimplemented function - T-enhancement?

**Comment by ultimaweapon** [comment]
Anything that is going to add a new functionality is `T-enhancement` and anything that is already implemented but somehow not working in some scenarios is `T-bug`.
