### ISSUE TITLE
Possibility to run user-define elf/bin files

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [obhq/obliteration#354]
Add experimental (you can mark it as unsafe or experimental) possibility to run user-defined (in GUI like: Open->Run elf/bin) PS4 executable files. I do have some homebrews/samples as elf files.

**Comment by VocalFan** [comment]
+1 this as ELF files are typically used as examples of an emulator working due to their simplicity. Besides from that, it also would let us test different functions of the emulator by running an ELF meant to do a specific task.

**Comment by VocalFan** [comment]
@ultimaweapon Can I potentially ask for a focus on this?

**Comment by ultimaweapon** [comment]
This one is a problem for us because our code structure was designed for big app like game only.

**Comment by ultimaweapon** [comment]
Now we have moved to a real kernel, which only works with a full PS4 system software. That mean we are no longer able to run an individual game (and ELF file) from the GUI.
