### ISSUE TITLE
Not Yet Implemented: sysctl CTL KERN:33

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#372]
Finally reached the end of my reign of pass as 0s.

```
++++++++++++++++++ I [00:00:00:00:964]:0x000000000000032c:kernel\src\syscalls\mod.rs:154
The virtual process become a group leader.
++++++++++++++++++ I [00:00:00:00:964]:0x000000000000032c:kernel\src\syscalls\mod.rs:62
Syscall called: 56
++++++++++++++++++ I [00:00:00:00:964]:0x000000000000032c:kernel\src\syscalls\mod.rs:62
Syscall called: 5
++++++++++++++++++ I [00:00:00:00:964]:0x000000000000032c:kernel\src\syscalls\mod.rs:62
Syscall called: 50
++++++++++++++++++ I [00:00:00:00:964]:0x000000000000032c:kernel\src\syscalls\mod.rs:62
Syscall called: 54
++++++++++++++++++ I [00:00:00:00:964]:0x000000000000032c:kernel\src\syscalls\mod.rs:62
Syscall called: 202
++++++++++++++++++ P [00:00:00:00:964]:0x000000000000032c:kernel\src\sysctl\mod.rs:69
not yet implemented: sysctl CTL_KERN:33
```

**Comment by VocalFan** [comment]
I am surprised I was able to make it this far, to be honest.

**Comment by red-prig** [comment]
I currently have:

//CTL_KERN identifiers
  KERN_PROC_ =14;
  KERN_USRSTACK =33;
  KERN_ARND =37;
  KERN_SDKVERSION=38; //SDK version

  KERN_SMP =$100; //(OID_AUTO) Kernel SMP
  KERN_SCHED =$101; //(OID_AUTO) Scheduler

**Comment by ultimaweapon** [comment]
Thanks!

**Comment by VocalFan** [comment]
> I currently have:
> 
> //CTL_KERN identifiers
>   KERN_PROC_ =14;
>   KERN_USRSTACK =33;
>   KERN_ARND =37;
>   KERN_SDKVERSION=38; //SDK version
> 
>   KERN_SMP =$100; //(OID_AUTO) Kernel SMP
>   KERN_SCHED =$101; //(OID_AUTO) Scheduler

Hey dude! Nice to see ya! (If you didn't realize, @ultimaweapon , this is the founder of fpPS4)

**Comment by ultimaweapon** [comment]
@red-prig do you have an [appinfo](https://github.com/obhq/obliteration/issues/318#issuecomment-1696669076) structure? If yes could you share with us?

**Comment by red-prig** [comment]
@ultimaweapon At the moment, I described it like this (apparently, only cusa_name/titleid is used inside the kernel and I defined the rest from user space libraries)
![app_info](https://github.com/obhq/obliteration/assets/68122101/3327668b-fc3c-4d11-83ee-bdcbb8e23be0)

**Comment by ultimaweapon** [comment]
I see. That why I never found the other fields in the kernel. Thanks!

**Comment by ultimaweapon** [comment]
@red-prig let me know if you need any information. I'm happy to share with you (and anyone who are interested) if I have that information.

**Comment by VocalFan** [comment]
Btw, I'll do another syscall reporting spree when this is added haha.
