### ISSUE TITLE
not yet implemented: sysctl 0

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [obhq/obliteration#386]
++++++++++++++++++ P [00:00:00:00:281]:0x0000000000005540:kernel\src\sysctl\mod.rs:56
not yet implemented: sysctl 0

**Comment by VocalFan** [comment]
This one seems Sony specific... 0 is unused in FreeBSD 9.1, but used on the latest FreeBSD version

**Comment by VocalFan** [comment]
And after this, prepare for Sysctl 6, CTL_HW, @ultimaweapon.

*With both CTL's returning Ok(0), I reach syscall 432*

**Comment by red-prig** [comment]
Look carefully sysctl 0 is an implicit call to sysctlbyname, the same thing exists in freebsd
