### ISSUE TITLE
Setup fails to manually pull files from PS4

### ISSUE THREAD

**Issue by hax4dazy** [obhq/obliteration#395]
The setup crashes when trying to download the firmware files though FTP. [Here is a video of the issue occurring](https://hax.1337.sx/WQV6e1XqEu.mp4) I am on firmware version 6.72 and I'm using goldhen as my FTP server

**Comment by ultimaweapon** [comment]
Thanks for the video.

**Comment by ultimaweapon** [comment]
The only possible cases are already fixed by https://github.com/obhq/obliteration/pull/424 so this should never happen again.
