### ISSUE TITLE
Fix syscall 610 to return a proper process type

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#411]
According to https://github.com/obhq/obliteration/issues/409#issuecomment-1775588844 it seems like we are currently booting the `libkernel` in system application mode, not a game mode. Right now we already have [IDT](https://github.com/obhq/obliteration/tree/main/src/kernel/src/idt) implementation so it should not too hard to fix syscall 610 with a proper implementation.

**Comment by VocalFan** [comment]
So, I assume no syscall skip-aheads until this is implemented

**Comment by ultimaweapon** [comment]
Let's see how far we can go without a proper implementation of this.

**Comment by VocalFan** [comment]
...Well, good thing is my replacement Mobo is coming today. *I got a new full-atx b550 board to replace my matx b450 board, however, the board was DOA x3*

**Comment by ultimaweapon** [comment]
Fixed by #469.
