### ISSUE TITLE
Not Yet Implemented: sysctl [1, 14, 41]

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#416]
```
++++++++++++++++++ I [00:00:00:01:584]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 557
++++++++++++++++++ I [00:00:00:01:584]:0x0000000000001bc0:kernel\src\process\mod.rs:441
Named object 'SceLibcI_FileStderr' (ID = 15) was created with data = 0x2000004c0 and flags = 0x101.
++++++++++++++++++ I [00:00:00:01:584]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 202
++++++++++++++++++ I [00:00:00:01:584]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 202
++++++++++++++++++ I [00:00:00:01:584]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 487
++++++++++++++++++ I [00:00:00:01:584]:0x0000000000001bc0:kernel\src\process\mod.rs:451
Returning bypass as 0.
++++++++++++++++++ I [00:00:00:01:584]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 340
++++++++++++++++++ I [00:00:00:01:585]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 340
++++++++++++++++++ I [00:00:00:01:585]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 596
++++++++++++++++++ I [00:00:00:01:585]:0x0000000000001bc0:kernel\src\process\mod.rs:451
Returning bypass as 0.
++++++++++++++++++ I [00:00:00:01:585]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 598
++++++++++++++++++ I [00:00:00:01:585]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 605
++++++++++++++++++ I [00:00:00:01:585]:0x0000000000001bc0:kernel\src\process\mod.rs:451
Returning bypass as 0.
++++++++++++++++++ I [00:00:00:01:585]:0x0000000000001bc0:kernel\src\syscalls\mod.rs:51
Syscall called: 202
++++++++++++++++++ P [00:00:00:01:585]:0x0000000000001bc0:kernel\src\sysctl\mod.rs:198
not yet implemented: sysctl [1, 14, 41]
```

Bypassed Syscalls: 487 | 596 | 605

**Comment by VocalFan** [comment]
@ultimaweapon I'ma be honest, Ultima. I'm amazing at how much I can just step ahead sometimes. Sure, it isn't intended behavior, but it shows a general path of what needs implemented next.

**Comment by ultimaweapon** [comment]
@SuchAFuriousDeath do you want to work on this? If yes better to assign yourself here so other people know they can't pick this issue to work on.

**Comment by SuchAFuriousDeath** [comment]
I'll try my best.

**Comment by SuchAFuriousDeath** [comment]
I can find the strings with the names, descriptions and formats of various oids in Ghidra, but there don't seem to be any references to them. And from the code, what seems to be the toplevel OidList, it's just a null pointer. Could you point me to the right place?. It would be much appreciated

**Comment by ultimaweapon** [comment]
It seems like you load the dumped kernel as ELF. You need to load as a raw binary to see the references to those items.

**Comment by SuchAFuriousDeath** [comment]
Well that's ... nice to hear :D

**Comment by red-prig** [comment]
CTL_KERN.KERN_PROC.KERN_PROC_SANITIZER

**Comment by SuchAFuriousDeath** [comment]
> It seems like you load the dumped kernel as ELF. You need to load as a raw binary to see the references to those items.

Ok, so I loaded it as a raw binary, but now the syscall table is at a different address than the one stated in https://github.com/obhq/obliteration/discussions/292

**Comment by SuchAFuriousDeath** [comment]
red-prig said on discord that the memory is supposed to be null, because it's initialized at runtime. He told me that I should look for the address of the top-most oid list. I found what seems to be several oids thanks to that, but the funny thing is that all of their handlers are null.

**Comment by SuchAFuriousDeath** [comment]
Ok, not all of them, but most

**Comment by ultimaweapon** [comment]
> > It seems like you load the dumped kernel as ELF. You need to load as a raw binary to see the references to those items.
> 
> Ok, so I loaded it as a raw binary, but now the syscall table is at a different address than the one stated in https://github.com/obhq/obliteration/discussions/292

You need to specify the same base address as ELF before loading.

**Comment by SuchAFuriousDeath** [comment]
@red-prig In my kernel, kern_sanitizer has number 29.

**Comment by SuchAFuriousDeath** [comment]
Ok. I'm dumb. It's 29 in hex, which is 41, of course :/

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon In a lot of functions, there's something like MOV RBX, qword ptr GS:[0x0]. From how the value in the register is treated, it seems to be a thread. Is that right?

**Comment by ultimaweapon** [comment]
It is FreeBSD `curthread`.

**Comment by SuchAFuriousDeath** [comment]
So our equivalent is VThread::current?

**Comment by ultimaweapon** [comment]
Correct.

**Comment by SuchAFuriousDeath** [comment]
In sysctl handlers, which argument is in the RCX register? I suppose it's req (type sysctl_req), if so, what are the fields and padding of this structure in the kernel? Might be a worthy addition to the wiki. I tried the one here https://github.com/freebsd/freebsd-src/blob/b2921fdc2330a5750f557fa321b94f972d5a7702/sys/sys/sysctl.h#L161-L174, but It doesn't seem right.

**Comment by SuchAFuriousDeath** [comment]
<img width="494" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/43a70988-72b9-4004-b3f9-fd6dd00141fd">

**Comment by red-prig** [comment]
sec

**Comment by red-prig** [comment]
![sysctl_oid](https://github.com/obhq/obliteration/assets/68122101/37690869-0c4f-43ed-b037-8d758275a591)
![sysctl_req](https://github.com/obhq/obliteration/assets/68122101/64f2d808-098d-403b-b542-7eae169f2d27)

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon What's the Obliteration equivalent of req->oldfunc(...) ?

**Comment by ultimaweapon** [comment]
`SysctlReq::write`.

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon Any idea what thread->proc->p_dynlib->field_0xfc is?

**Comment by SuchAFuriousDeath** [comment]
It seems to be 4 bytes long

**Comment by red-prig** [comment]
Uh, in short, I called this field Sanitizer because it’s actually a boolean value 0/1 that indicates whether the sanitizer is turned on, so generally speaking you can just return 0 as a response

**Comment by ultimaweapon** [comment]
What I have is bit flags:

```
0x01 = Hash libSceDbgUndefinedBehaviorSanitizer in needed module, 0x02 = Has libSceDbgAddressSanitizer in the needed module
```

Our implementation: https://github.com/obhq/obliteration/blob/main/src/kernel/src/rtld/mod.rs#L123

**Comment by SuchAFuriousDeath** [comment]
The flags we have currently are u8, but this syscall writes 4 bytes. I assume I should change the flags to be u32 then?
And also, what do I pass to Sysctl in the new function, just the flags? Passing the whole linker would mean making Sysctl generic over ExecutionEngine.

**Comment by ultimaweapon** [comment]
> The flags we have currently are u8, but this syscall writes 4 bytes. I assume I should change the flags to be u32 then?

Correct. I was using u8 because I'm not sure about its size. Now this has proved it is 4 bytes.

> And also, what do I pass to Sysctl in the new function, just the flags? Passing the whole linker would mean making Sysctl generic over ExecutionEngine.

Yeah pass the whole linker. EE is going to be the one and the only generic parameter at the global level.

**Comment by SuchAFuriousDeath** [comment]
But handlers would have to be generic too.
<img width="648" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/0d5f4884-5029-4068-8467-3fc48cc813b7">

**Comment by SuchAFuriousDeath** [comment]
Maybe we could create a field like linkerInfo, put the flags in that and pass that to sysctl.

**Comment by ultimaweapon** [comment]
> But handlers would have to be generic too.
> <img width="648" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/0d5f4884-5029-4068-8467-3fc48cc813b7">
> -> so Oids will have to be generic too
> 

Try moving the table to the associated constant.

**Comment by SuchAFuriousDeath** [comment]
You mean like trait ExecutionEngine { ... type OidTable ...}?

**Comment by ultimaweapon** [comment]
I mean moving `CHILDREN` to inside `impl Sysctl {`.

**Comment by SuchAFuriousDeath** [comment]
Oh. ok then

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon This only writes the flags if a certain function returns true, otherwise it writes 0u32. Unfortunately, I'm not sure what this function is.

**Comment by ultimaweapon** [comment]
Choose one branch that works and put TODO for another branch.

**Comment by SuchAFuriousDeath** [comment]
Well, red prig says we could just return 0. So I'll pick that.
