### ISSUE TITLE
SIGSEGV on xsave64 instruction

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#419]
<img width="465" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/f8acbaa2-01e5-4695-bc61-a91a7b872a24">
This instruction causes a SIGSEGV for me. It's located in the patched ELF file. I think my xsave_area is too big (2696 bytes). When my friend with the same OS sends me his compiled kernel binary, the error happens for me when I run it, but not for him, his xsize_area is 1088. When I put in 1088 for myself, it passes the xsave64 instruction and crashes on one of the next instructions.

The assembly instruction corresponds to this line - https://github.com/obhq/obliteration/blob/5bdc59ec6b426963fa7222ac6280af47b893c0ab/src/kernel/src/ee/native/mod.rs#L526-L533

Maybe the xsave area is too big to subtract from rsp? I'm not sure, I hope someone has in idea of what's happening here

**Comment by SuchAFuriousDeath** [comment]
My friend gets the exact same error I do and on the same instruction, when he sets the xsave_area to 2696

**Comment by VocalFan** [comment]
Replicated on Windows:
Xsave area init: 2696
++++++++++++++++++ I [00:00:00:00:422]:0x0000000000004934:kernel\src/main.rs:194
Loading /system/common/lib/libkernel.sprx.
Xsave area aligned: 2704 (x198 times)
![image](https://github.com/obhq/obliteration/assets/45863583/7775aca6-bae5-48f4-81c9-eda679ac4f72)

**Comment by KevinHlavaty** [comment]
I was getting the exact same error. I don't believe it's because xsave_area is too big, as another way I could solve the error was actually making xsave_area larger. I believe the issue is rsp not being aligned to a 64-byte boundary, which the documentation says is required. Every time it crashed for me, rsp was not 64-byte aligned, and making it 64-byte aligned fixed the problem. I'm not sure the best way to implement that fix though

**Comment by VocalFan** [comment]
> I was getting the exact same error. I don't believe it's because xsave_area is too big, as another way I could solve the error was actually making xsave_area larger. I believe the issue is rsp not being aligned to a 64-byte boundary, which the documentation says is required. Every time it crashed for me, rsp was not 64-byte aligned, and making it 64-byte aligned fixed the problem. I'm not sure the best way to implement that fix though

For anyone wanting this, just change 

`let xsave = (self.xsave_area + 15) & !15;` to `let xsave = (self.xsave_area + 63) & !63;`

**Comment by SuchAFuriousDeath** [comment]
oh, interesting

**Comment by SuchAFuriousDeath** [comment]
> I was getting the exact same error. I don't believe it's because xsave_area is too big, as another way I could solve the error was actually making xsave_area larger. I believe the issue is rsp not being aligned to a 64-byte boundary, which the documentation says is required. Every time it crashed for me, rsp was not 64-byte aligned, and making it 64-byte aligned fixed the problem. I'm not sure the best way to implement that fix though

I confirm this fixed the issue
