### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#420]
A popular feature among most modern games and emulators, it allows people to see what game you're playing. Seeing as I suck at Reverse Engineering, I'll try to do this haha. *Also, should I use Tokio for Async?*

Possible design:
```
               Obliteration
LOGO           Game - NPUB
               Time Elapsed
```

**Comment by VocalFan** [comment]
@ultimaweapon Current progress:

![image](https://github.com/obhq/obliteration/assets/45863583/90532d53-c045-40e3-98b9-62bb59bc2abc)

How might I be able to get the game name? After all, this is running in the Kernel as a thread... Which is Rust. And I can't see where I could get the name from the kernel.

**Comment by ultimaweapon** [comment]
You can get the game name from `param.sfo`. See https://github.com/obhq/obliteration/blob/main/src/kernel/src/fs/mod.rs for an example.

**Comment by VocalFan** [comment]
Well, I found it here: https://github.com/obhq/obliteration/blob/main/src/param/src/lib.rs#L131

But I have no clue how to read this XD

*Note, the discord_presence folder contains a mod.rs file that is then called by the kernel.*

**Comment by VocalFan** [comment]
```rs
use crate::{info, warn};
use discord_rich_presence::{activity, DiscordIpc, DiscordIpcClient};
use std::time::SystemTime;

fn format_duration(secs: u64) -> String {
    let hours = secs / 3600;
    let minutes = (secs % 3600) / 60;
    let seconds = secs % 60;

    if hours > 0 {
        format!("{} hour{} and {} minute{}", hours, if hours == 1 { "" } else { "s" }, minutes, if minutes == 1 { "" } else { "s" })
    } else if minutes > 0 {
        format!("{} minute{} and {} second{}", minutes, if minutes == 1 { "" } else { "s" }, seconds, if seconds == 1 { "" } else { "s" })
    } else {
        format!("{} second{}", seconds, if seconds == 1 { "" } else { "s" })
    }
}


pub async fn rich_presence(titleid: &String) -> Result<(), Box<dyn std::error::Error>> {
    info!("Initializing Discord rich presence.");
    let mut client = match DiscordIpcClient::new("1168617561244565584") {
        Ok(client) => client,
        Err(e) => {
            warn!("Failed to create Discord IPC: {:?}", e);
            return Err(e.into());
        }
    };

    if let Err(e) = client.connect() {
        warn!("Failed to connect to Discord client: {:?}", e);
        return Err(e.into());
    }

    let start_time = SystemTime::now();
    loop {
        let elapsed = start_time.elapsed()?.as_secs();
        let details_text = &format!("Playing NAME - {}", titleid);
        let state_text = format!("For {}", format_duration(elapsed));
        let payload = activity::Activity::new()
            .details(details_text)
            .state(&state_text)
            .assets(
                activity::Assets::new()
                    .large_image("obliteration-icon")
                    .large_text("Obliteration")
            );
            if let Err(e) = client.set_activity(payload) {
                warn!("Failed to update Discord presence: {:?}", e);
                return Err(e.into());
            }

        tokio::time::sleep(std::time::Duration::from_secs(1)).await;
    }
}
```

**Comment by VocalFan** [comment]
...And I get the TitleID currently by just the last part of the folder path lmao *After all, games only run from their install folders...*

**Comment by VocalFan** [comment]
Might've found the answer to my question, and I'll use it to get Title_ID as well from Param instead of depending on the path.

**Comment by ultimaweapon** [comment]
Adding an async-runtime like Tokio just for this thing is too much. Better to use a synchronous version instead.

**Comment by VocalFan** [comment]
> Adding an async-runtime like Tokio just for this thing is too much. Better to use a synchronous version instead.

...It kind of has to run separately from the kernel. Seeing as it has to refresh the Presence every second, which I'd rather not hitch the kernel for a moment on that. Even then, when the kernel crashes, the Discord thread exits too and removes the status. *Instead of the infamous infinite-status that can happen if an app doesn't take a moment to end the presence.*

**Comment by VocalFan** [comment]
But I guess I could try to see if I can make it sync... Somehow? Not sure how I would. Especially since it has to loop.

**Comment by VocalFan** [comment]
Might've found a way... Might. I'll test to see if this supports Timestamps.

**Comment by VocalFan** [comment]
It was mainly for the Format_Duration function and state_text, but as I said, I can most likely just use Discord's timestamp support.

**Comment by VocalFan** [comment]
Well, I got it running! But uh, issue...

**Comment by VocalFan** [comment]
Whenever I have the function return `Ok(())`, the activity disappears.

**Comment by VocalFan** [comment]
So I think I need to keep it Async?

**Comment by VocalFan** [comment]
I got it working! Just had to assign the client to an unused variable.
