### ISSUE TITLE
Getting this on the linux flatpak issue when running games.

### ISSUE THREAD

**Issue by zqpvr** [obhq/obliteration#430]
```++++++++++++++++++ I [00:00:00:00:005]:0x0000000000000022:kernel/src/discord_presence/mod.rs:29
Initializing Discord rich presence.
Application Title  : pacman
Application TitleID: PCMN99999
++++++++++++++++++ W [00:00:00:00:006]:0x0000000000000022:kernel/src/discord_presence/mod.rs:48
Failed to connect to Discord client: Couldn't connect to the Discord IPC socket.
++++++++++++++++++ I [00:00:00:00:006]:0x0000000000000022:kernel/src/main.rs:99
Starting Obliteration Kernel.
System directory    : /home/deck/Documents/PS4
Game directory      : /home/deck/Documents/PS4-Games/PCMN99999
Debug dump directory: /home/deck/.var/app/io.github.obhq.Obliteration/data/OBHQ/Obliteration/kernel
++++++++++++++++++ I [00:00:00:00:006]:0x0000000000000022:kernel/src/main.rs:132
Page size             : 0x1000
Allocation granularity: 0x1000
Main stack            : 0x7effe3200000:0x7effe3400000
++++++++++++++++++ I [00:00:00:00:006]:0x0000000000000022:kernel/src/main.rs:199
Initializing runtime linker.
++++++++++++++++++ I [00:00:00:00:217]:0x0000000000000022:kernel/src/main.rs:211
Application   : /mnt/sandbox/PCMN99999_000/app0/eboot.bin
Image format  : SELF
Image type    : ET_SCE_DYNEXEC
Program 0     : 0x0000000000004000:0x00000000014ba2c4 => 0x0000000000000000:0x00000000014b62c4 PT_LOAD
Program 1     : 0x00000000014bc000:0x0000000001502e50 => 0x00000000014b8000:0x0000000001500000 PT_SCE_RELRO
Program 2     : 0x0000000001504000:0x0000000001522d88 => 0x0000000001500000:0x0000000001651d70 PT_LOAD
Program 3     : 0x0000000001504000:0x0000000001504050 => 0x0000000001500000:0x0000000001500050 PT_SCE_PROCPARAM
Program 4     : 0x00000000015fa7b0:0x00000000015fb310 => 0x0000000000000000:0x0000000000000b60 PT_DYNAMIC
Program 5     : 0x0000000000004000:0x0000000000004015 => 0x0000000000000000:0x0000000000000015 PT_INTERP
Program 6     : 0x0000000001504060:0x0000000001504060 => 0x0000000001500060:0x0000000001500080 PT_TLS
Program 7     : 0x0000000001473ad0:0x00000000014ba2c4 => 0x000000000146fad0:0x00000000014b62c4 PT_GNU_EH_FRAME
Program 8     : 0x0000000001522dc0:0x00000000015fb310 => 0x0000000000000000:0x0000000000000000 PT_SCE_DYNLIBDATA
Program 9     : 0x00000000015fb310:0x00000000015fb378 => 0x0000000000000000:0x0000000000000000 PT_SCE_COMMENT
Program 10    : 0x00000000015fb378:0x00000000015fbd8e => 0x0000000000000000:0x0000000000000000 PT_SCE_VERSION
Needed        : libSceNetCtl.prx
Needed        : libSceSysmodule.prx
Needed        : libSceNet.prx
Needed        : libSceGnmDriver.prx
Needed        : libSceUserService.prx
Needed        : libSceVideoOut.prx
Needed        : libSceAudioOut.prx
Needed        : libSceAudioIn.prx
Needed        : libScePad.prx
Needed        : libSceMove.prx
Needed        : libSceIme.prx
Needed        : libkernel.prx
Needed        : libSceRtc.prx
Needed        : libSceFios2.prx
Needed        : libSceSystemService.prx
Needed        : libSceHttp.prx
Needed        : libSceSsl.prx
Needed        : libSceSaveData.prx
Needed        : libSceCommonDialog.prx
Needed        : libSceAvPlayer.prx
Needed        : libSceAppContent.prx
Needed        : libSceWebBrowserDialog.prx
Needed        : libSceAudio3d.prx
Needed        : libSceAjm.prx
Needed        : libSceSocialScreen.prx
Needed        : libSceHmd.prx
Needed        : libSceVrTracker.prx
Needed        : libSceHmdSetupDialog.prx
Needed        : libSceCamera.prx
Needed        : libSceRemoteplay.prx
Needed        : libSceNpWebApi.prx
Needed        : libSceNpCommon.prx
Needed        : libSceNpManager.prx
Needed        : libSceMouse.prx
Needed        : mono-ps4.prx
Needed        : MonoAssembliesPS4.prx
Needed        : libc.prx
Symbol count  : 816
Module flags  : MAIN_PROG | TEXT_REL | UNK2
TLS index     : 1
Memory address: 0x00007effe15a4000:0x00007effe31f8000
Initialization: 0x00007effe19a4020
Entry address : 0x00007effe19a4080
Finalization  : 0x00007effe2b9a0c0
TLS init      : 0x00007effe2ea4060:0x00007effe2ea4060
TLS size      : 32
EH header     : 0x00007effe2e13ad0:0x00007effe2e5a2c4
EH frame      : 0x00007effe2d0e32c:0x00007effe2e13ad0
Process param : 0x00007effe2ea4000:0x00007effe2ea4050
SDK version   : 0x04508101
Program 0 is mapped to 0x00007effe19a4000:0x00007effe2e5c000 with EXECUTE | READ.
Program 1 is mapped to 0x00007effe2e5c000:0x00007effe2ea4000 with READ.
Program 2 is mapped to 0x00007effe2ea4000:0x00007effe2ff8000 with WRITE | READ.
++++++++++++++++++ I [00:00:00:00:217]:0x0000000000000022:kernel/src/main.rs:223
Loading /system/common/lib/libkernel.sprx.
++++++++++++++++++ E [00:00:00:00:217]:0x0000000000000022:kernel/src/main.rs:228
Load failed: cannot open (S)ELF -> invalid ELF magic.```

**Comment by ultimaweapon** [comment]
It seems like your firmware files are corrupted.

**Comment by VocalFan** [comment]
To be fair @ultimaweapon They had an issue FTPing on the Flatpak version with

```
`Failed to download system files from 192.168.1.30:2121 to /home/deck/Documents/PS4: cannot retrieve /system/sys/GnmCompositor.elf -> cannot open a data connection to 192.168.1.30:63922 -> Too many open files (os error 24)`
```

However, they said using WINE on the Windows version worked... Seems they probably used the same folder.

**Comment by ultimaweapon** [comment]
Strange. It should open at most 3 FDs per file.

**Comment by ultimaweapon** [comment]
The only cases I can think is Rust inline this function https://github.com/obhq/obliteration/blob/main/src/core/src/fwdl.rs#L105 and cause `dst` and `src` not dropped on each file.

**Comment by Quackdoc** [comment]
`Too many open files (os error 24)` is an OS issue, usually on distros like KDE where max file descriptors are set to a low number. this can cause all sorts of issues, some that go noticed, some that don't. 

an example of such an issue is here https://discussion.fedoraproject.org/t/running-out-of-file-handles-in-pipewire/85544/10

**Comment by Quackdoc** [comment]
> so how would I fix it?

the link I replied with has a potential fix

**Comment by VocalFan** [comment]
Not really a fix as it modifys the hard limit... But even then the USER has to do it.

**Comment by ultimaweapon** [comment]
So this is a limit per user that shared with multiple processes?

**Comment by Quackdoc** [comment]
> Not really a fix as it modifys the hard limit... But even then the USER has to do it.

while I do agree, this is not something obliteration can solve, the fix 

> So this is a limit per user that shared with multiple processes?

it's a little complicated on how it works, but the TLDR is that you have both Global limits, and Per process limits. and then there are some hidden shared limits. 

On some distros the hard limit is set to 4096 (`ulimit -Hn` should show the max hard limit) if this is the case then it's possible if obliteration is surpassing this, however most distros now should have a hard limit surpassing 9999 and a soft limit of around 1024 (a soft limit will not immediately cause the os to reject you.)

I wouldn't remove the possibility of flatpak imposing their own file limits too. It could be global limits, could be process limits or could be typical linux jank. but in the end, unless obliteration is doing something *really weird*, this is likely just either distro or flatpak shenanigans

**Comment by ultimaweapon** [comment]
@zqpvr can you run `ulimit -Hn` to see what is the hard-limit on your machine?

**Comment by Quackdoc** [comment]
While that is a but on the lower side, I don't think that would be low enough to cause issues however I have found multiple other users with similar issues so it seems like it's not an isolated case. I really don't think the hard limit should be an issue here though considering it's so high.

Im thinking this is likely a steamdeck specific issue after some digging, there was some issues with how flatpak and ostree interact with eachother in the past, and this is very reminicent of it

Past issues;
https://github.com/flatpak/flatpak/issues/4928
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1783
https://github.com/flatpak/flatpak/issues/5078

Other Users;
https://gist.github.com/stefanocoding/ec7d54116559781455d67019439e4ae5

https://www.reddit.com/r/SteamDeckEmu/comments/17op8fd/having_issues_updating_38_files_on_my_steam_deck/
https://www.reddit.com/r/SteamDeck/comments/1623nw8/help_with_discover_updates_too_many_open_files/

**Comment by ultimaweapon** [comment]
@zqpvr can you test this? https://github.com/obhq/obliteration/pull/441

**Comment by ultimaweapon** [comment]
> @ultimaweapon I will test when I get home tommorow, also I assume you got a flatpak build for this?

You can download Flatpack build from the CI of that PR.

**Comment by ultimaweapon** [comment]
You need to go to the `Summary` tab. Here is the link: https://github.com/obhq/obliteration/actions/runs/6893625865?pr=441

**Comment by ultimaweapon** [comment]
Thanks for testing!

**Comment by ultimaweapon** [comment]
@SuchAFuriousDeath are currently working on this. See #416 for the the corresponding issue.
