### ISSUE TITLE
Implement /dev/dipsw ioctl

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#437]
Before hitting sys_dynlib_unload_prx (see #436) stops us from proceeding further, the PS4 tries to:
- open /dev/dipsw
- perform ioctl on it

Both of those are currently unimplemented.
Related: #434

**Comment by SuchAFuriousDeath** [comment]
After opening /dev/dipsw, it tries to ioctl on it

**Comment by ultimaweapon** [comment]
Better to make this issue specific to `/dev/dipsw` because it is what block us right now.
