### ISSUE TITLE
Implement sysctl name2oid(machdep.tsc_freq)

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#439]
Happens after bypassing #435

**Comment by SuchAFuriousDeath** [comment]
After returning ENOENT, we get a segmentation fault. Probably caused by some other syscall returning a bad value.

**Comment by SuchAFuriousDeath** [comment]
The handler seems to be fiddling with a lot of static data

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon FYI, I tried the crate 'rawtime' to get the frequency and it seems to work, PR coming soon. We should probably wait until all the preceding syscalls are implemented to make sure it really does return a correct value.

**Comment by VocalFan** [comment]
> @ultimaweapon FYI, I tried the crate 'rawtime' to get the tsc frequency and it seems to work , PR coming soon. We should probably wait until all the preceding syscalls are implemented to make sure it really does return a correct value to merge this one. EDIT: Unfortunately, VocalFan found out it requires the nightly compiler, so I guess it's off limits. We can still get inspired by the code to make our own implementation, though, shouldn't be too hard.

But I did get our own WIP implementation. Should be accurate enough for the emu.

```rs
use std::time::{Duration, Instant};

/// Estimate TSC frequency off 1ms
fn estimate_tsc_frequency() -> u64 {
    let duration = Duration::from_millis(1);
    let start = Instant::now();
    let start_tsc = unsafe { std::arch::x86_64::_rdtsc() };

    while Instant::now().duration_since(start) < duration {
        // Busy-wait
    }

    let end_tsc = unsafe { std::arch::x86_64::_rdtsc() };
    let elapsed = end_tsc - start_tsc;

    // Multiply to get full second estimate.
    (elapsed as u64) * 1000 
}
```

**Comment by ultimaweapon** [comment]
> > @ultimaweapon FYI, I tried the crate 'rawtime' to get the tsc frequency and it seems to work , PR coming soon. We should probably wait until all the preceding syscalls are implemented to make sure it really does return a correct value to merge this one. EDIT: Unfortunately, VocalFan found out it requires the nightly compiler, so I guess it's off limits. We can still get inspired by the code to make our own implementation, though, shouldn't be too hard.
> 
> But I did get our own WIP implementation. Should be accurate enough for the emu.
> 
> ```rs
> use std::time::{Duration, Instant};
> 
> /// Estimate TSC frequency off 1ms
> fn estimate_tsc_frequency() -> u64 {
>     let duration = Duration::from_millis(1);
>     let start = Instant::now();
>     let start_tsc = unsafe { std::arch::x86_64::_rdtsc() };
> 
>     while Instant::now().duration_since(start) < duration {
>         // Busy-wait
>     }
> 
>     let end_tsc = unsafe { std::arch::x86_64::_rdtsc() };
>     let elapsed = end_tsc - start_tsc;
> 
>     // Multiply to get full second estimate.
>     (elapsed as u64) * 1000 
> }
> ```

This will not work on non-x86.

**Comment by VocalFan** [comment]
I noticed, Ultima, that's why it's WIP lol.

**Comment by VocalFan** [comment]
Okay so, ARM is kind of... Screwed. Unless if we ONLY use Nightly rust. Reason is ARM would need asm! to do this.

**Comment by SuchAFuriousDeath** [comment]
@VocalFan Don't we already use asm! ?

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon Are you working on this? I can do it if you want to.

**Comment by SuchAFuriousDeath** [comment]
Oh, I just noticed that I'm already assigned to this :D

**Comment by ultimaweapon** [comment]
@red-prig do you know why the PS4 query this value from the kernel? Does it use this value to operate the timers?

**Comment by red-prig** [comment]
Somewhere it is used, for example:

```
long sceKernelGetTscFrequency(void)

{
  undefined8 len;
  long _guard;
  
  _guard = __stack_chk_guard;
  if (tsc_freq == 0) {
    len = 8;
    sysctlbyname("machdep.tsc_freq",&tsc_freq,&len,0,0);
  }
  if (__stack_chk_guard == _guard) {
    return tsc_freq;
  }
                    /* WARNING: Subroutine does not return */
  __stack_chk_fail();
}
```

**Comment by red-prig** [comment]
It is quite logical that the frequency of the system timer is requested, naturally to convert the counter into seconds/microseconds, etc.

**Comment by ultimaweapon** [comment]
Thanks.
