### ISSUE TITLE
Linux Mint Cinnamon - Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#440]
Occurs when launching Obliteration after freshly installing the flatpak, leading to the application to being on light mode instead of following the gtk theme.
![image](https://github.com/obhq/obliteration/assets/45863583/5f598144-c0d3-4305-a68d-83d242c34aaa)

**Comment by VocalFan** [comment]
@ultimaweapon Just saying, FTP worked properly on Mint! No limit error.

**Comment by ultimaweapon** [comment]
Try https://askubuntu.com/a/1417077.

**Comment by VocalFan** [comment]
```

The following packages have unmet dependencies:
 xapp : Depends: libxapp1 (= 2.2.8-1) but 2.6.1+victoria is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by ultimaweapon** [comment]
With #1140 this problem should automatically fixed.
