### ISSUE TITLE
Discord Bot repo

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#457]
@ultimaweapon Can you create a repo for the Discord bot I use in the discord server?

Like... `discord-oboteration` or something. That way server members can contribute to the bot with new features. 

*We have it where the bot can give update files with `!update TitleID`, make a summary of log files, and list links to our emulator github, compatibility github, and website.*

**Comment by ultimaweapon** [comment]
https://github.com/obhq/discord-bot
