### ISSUE TITLE
Find out budget parameters for the game process

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#461]
I suspect it get called by SceSysCore.

**Comment by ultimaweapon** [comment]
@red-prig do you have any idea?

**Comment by VocalFan** [comment]
@ultimaweapon Tried checking, he just returns Enosys.

**Comment by red-prig** [comment]
571 = int sys_budget_set (int key)

```
function sys_budget_set(key:Integer):Integer;
begin
 Exit(ENOSYS); //sceSblACMgrIsSystemUcred
end;
```

**Comment by red-prig** [comment]
If you have system rights, this function sets the budget identifier for this process.

**Comment by red-prig** [comment]
If running via SceSysCore, save the value and return 0.

**Comment by ultimaweapon** [comment]
> If running via SceSysCore, save the value and return 0.

Yeah this is what I'm looking for. Do you know how this syscall get called before the game binary got exec?

**Comment by red-prig** [comment]
First, rfork_thread is called to create a new process, then parameters are loaded in the entry procedure, and only after that execve is called, switching the execution point to another file.

[processSpawn.txt](https://github.com/obhq/obliteration/files/13464114/processSpawn.txt)

[entry.txt](https://github.com/obhq/obliteration/files/13464115/entry.txt)

**Comment by ultimaweapon** [comment]
Thanks!

**Comment by ultimaweapon** [comment]
Our new target is syscall 568, which is used to create a budget. We need to find what budget it is created for a game process.

**Comment by ultimaweapon** [comment]
With our kernel-mode kernel we don't need this anymore.
