### ISSUE TITLE
Implement /dev/deci_tty6

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#470]
Now with #469 the firmware is asking for this file.

**Comment by ultimaweapon** [comment]
@VocalFan can you check if this file exists on the actual console? I suspect it will exists only on the dev machine.

**Comment by VocalFan** [comment]
Aight, just got my PS4 brought to my other place.

**Comment by VocalFan** [comment]
![image](https://github.com/obhq/obliteration/assets/45863583/a4fd10e6-20ef-4372-98cc-0bc17b469f8d)
It's there.

**Comment by SuchAFuriousDeath** [comment]
It seems that the PS4 just opens this and then does nothing with at, at least for now.

**Comment by SuchAFuriousDeath** [comment]
So this should be trivial to implement
