### ISSUE TITLE
SIGSEGV in Assassin's Creed 4: Black Flag

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#473]
After implementing machdep.tsc_freq, we get a random segfault.

**Comment by ultimaweapon** [comment]
This is a good news. The reason is because this crash happened in the game code, not the firmware! That mean the execution has been reached the game.

**Comment by ultimaweapon** [comment]
You can look at the address where it crashes. Then look at our logs to see where is that address are in. The next step is to figure out why it is crashed.

**Comment by ultimaweapon** [comment]
Here is an example. Mine crashed at 0x7FFFF7200770:

```
++++++++++++++++++ I [00:00:00:00:219]:0x000000000000ee42:kernel/src/main.rs:271
Application   : /mnt/sandbox/CUSA13434_000/app0/eboot.bin
Image format  : SELF
Image type    : ET_SCE_DYNEXEC
Program 0     : 0x0000000000004000:0x00000000003b3dc0 => 0x0000000000000000:0x00000000003afdc0 PT_LOAD
Program 1     : 0x00000000003b4000:0x00000000003c42e8 => 0x00000000003b0000:0x00000000003c4000 PT_SCE_RELRO
Program 2     : 0x00000000003c8000:0x00000000003f7138 => 0x00000000003c4000:0x00000000003f9a00 PT_LOAD
Program 3     : 0x00000000003c8000:0x00000000003c8050 => 0x00000000003c4000:0x00000000003c4050 PT_SCE_PROCPARAM
Program 4     : 0x0000000000423930:0x00000000004241d0 => 0x0000000000000000:0x00000000000008a0 PT_DYNAMIC
Program 5     : 0x0000000000004000:0x0000000000004015 => 0x0000000000000000:0x0000000000000015 PT_INTERP
Program 6     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_TLS
Program 7     : 0x00000000003a0fa4:0x00000000003b3dc0 => 0x000000000039cfa4:0x00000000003afdc0 PT_GNU_EH_FRAME
Program 8     : 0x00000000003f7140:0x00000000004241d0 => 0x0000000000000000:0x0000000000000000 PT_SCE_DYNLIBDATA
Program 9     : 0x00000000004241d0:0x0000000000424218 => 0x0000000000000000:0x0000000000000000 PT_SCE_COMMENT
Program 10    : 0x0000000000424218:0x000000000042491f => 0x0000000000000000:0x0000000000000000 PT_SCE_VERSION
Needed        : libSceUserService.prx
Needed        : libSceAjm.prx
Needed        : libScePad.prx
Needed        : libSceAvPlayer.prx
Needed        : libSceAudioOut.prx
Needed        : libSceGnmDriver.prx
Needed        : libSceVideoOut.prx
Needed        : libSceCommonDialog.prx
Needed        : libSceSaveDataDialog.prx
Needed        : libSceSaveData.prx
Needed        : libSceWebBrowserDialog.prx
Needed        : libSceNpToolkit2.prx
Needed        : libSceNpCommon.prx
Needed        : libSceNpManager.prx
Needed        : libSceNpUtility.prx
Needed        : libSceImeDialog.prx
Needed        : libSceAppContent.prx
Needed        : libSceSysmodule.prx
Needed        : libkernel.prx
Needed        : libSceSystemService.prx
Needed        : libc.prx
Needed        : libSceMsgDialog.prx
Needed        : libSceUsbd.prx
Needed        : libSceNpCommerce.prx
Needed        : libSceErrorDialog.prx
Needed        : libSceIme.prx
Symbol count  : 521
Module flags  : MAIN_PROG | TEXT_REL | UNK2
TLS index     : 1
Memory address: 0x00007ffff6b18000:0x00007ffff7614000
Initialization: 0x00007ffff6f18020
Entry address : 0x00007ffff718c120
Finalization  : 0x00007ffff71ff120
TLS init      : 0x00007ffff6f18000:0x00007ffff6f18000
TLS size      : 0
EH header     : 0x00007ffff72b4fa4:0x00007ffff72c7dc0
EH frame      : 0x00007ffff7270010:0x00007ffff72b4fa4
Process param : 0x00007ffff72dc000:0x00007ffff72dc050
SDK version   : 0x05508001
Program 0 is mapped to 0x00007ffff6f18000:0x00007ffff72c8000 with EXECUTE | READ.
Program 1 is mapped to 0x00007ffff72c8000:0x00007ffff72dc000 with READ.
Program 2 is mapped to 0x00007ffff72dc000:0x00007ffff7314000 with WRITE | READ.
```

You will see the location is in the range of `Memory address: 0x00007ffff6b18000:0x00007ffff7614000`.

**Comment by SuchAFuriousDeath** [comment]
That means I should probably rename this.

**Comment by SuchAFuriousDeath** [comment]
Thanks, by the way.

**Comment by ultimaweapon** [comment]
I found the reason now. It is because the game try to call the external function, which is not resolved by the relocation process. The problem is why the firmware does not load the other libraries. @red-prig do you have any idea? The last SPRX that was loaded is `libSceSysmodule.sprx`.

**Comment by red-prig** [comment]
At the end of libkernel initialization, the sceSysmodulePreloadModuleForLibkernel function from the libSceSysmodule module is requested and then called. It is inside sceSysmodulePreloadModuleForLibkernel that all the necessary libraries should be loaded, why this does not happen I can’t say for sure, many different parameters are requested there, somewhere in the middle of this year I painfully debugged it.

**Comment by ultimaweapon** [comment]
Thanks!

**Comment by ultimaweapon** [comment]
@VocalFan can you dump auth info for CUSA12380? Here is the payload. It will dump `/mnt/sandbox/pfsmnt/CUSA12380-app0/eboot.bin`.

[dump-auth.zip](https://github.com/obhq/obliteration/files/13537079/dump-auth.zip)

**Comment by VocalFan** [comment]
Compile one for CUSA02480 as well. That way we can check if there's a difference

**Comment by VocalFan** [comment]
> @VocalFan can you dump auth info for CUSA12380? Here is the payload. It will dump `/mnt/sandbox/pfsmnt/CUSA12380-app0/eboot.bin`.

Wrong path.

`/mnt/sandbox/pfsmnt/CUSA12380_000/app0/eboot.bin`

**Comment by VocalFan** [comment]
Oh, sorry.

**Comment by VocalFan** [comment]
*And should I get a notification when successful?*

**Comment by ultimaweapon** [comment]
> *And should I get a notification when successful?*

Yeah there will be a notification. It will save to `auth-info.bin` on the root of USB drive.

**Comment by VocalFan** [comment]
Yeah, buddy, I have no file.

**Comment by VocalFan** [comment]
I know it atleast sees the auth info, as I get an "not found" error with the game closed, but then I get nothing with the game running/suspended.

**Comment by VocalFan** [comment]
![image](https://github.com/obhq/obliteration/assets/45863583/532a7169-634e-4d86-9c09-1156d406b664)
But yeah, my USB has nothing... I mean, I have the whole game still on my usb SSD as visible on the top.

**Comment by ultimaweapon** [comment]
Does the game running? If yes try to close the game before running the payload.

**Comment by VocalFan** [comment]
![image](https://github.com/obhq/obliteration/assets/45863583/3ce668ff-7195-4aa3-8d18-2c7f09854a17)
Not in /mnt/sandbox/pfsmnt

**Comment by VocalFan** [comment]
Only things mounted at Payload Guest and my animated background.

**Comment by VocalFan** [comment]
Wait, do you just want the bin file?

**Comment by VocalFan** [comment]
Payload without game running:
*Notification of Payload received on 127.0.0.1*

"Failed to dump auth info."

Payload with game running:

*Notification of Payload received on 127.0.0.1*

Nothing.

**Comment by ultimaweapon** [comment]
This one is... a fake SELF. Do you have any retailed games installed?

**Comment by VocalFan** [comment]
Ah, yeah, Persona 5 Dancing is one of my backuped games... Let me check- Oh, yeah, my actual disc copy.

https://serialstation.com/titles/CUSA/17416

CUSA17416.

**Comment by ultimaweapon** [comment]
Okay, wait a moment. I'll build the payload for this one.

**Comment by ultimaweapon** [comment]
Here for CUSA17416:
[dump-auth.zip](https://github.com/obhq/obliteration/files/13538070/dump-auth.zip)

**Comment by VocalFan** [comment]
But yeah, Ultima, the Dancing games are backups I did. My PS4 corrupted once on a kernel-hang.

**Comment by ultimaweapon** [comment]
You mean your PS4 can't boot the retailed games anymore?

**Comment by VocalFan** [comment]
No, more like I just immediately jail-broke it again lmao.

**Comment by VocalFan** [comment]
So I mainly just grabbed all my digital games from my ObliterationGames folder, fPKG'd them, put them on my PS4. But my disc copies of games are installed normally.

**Comment by ultimaweapon** [comment]
> But my disc copies of games are installed normally.

Yeah we need to auth info from the eboot.bin of this one, not the one that installed from a Fake PKG.

**Comment by VocalFan** [comment]
Yeah, that's why I had you send one for Persona 5 Royal :P

**Comment by ultimaweapon** [comment]
> Here for CUSA17416: [dump-auth.zip](https://github.com/obhq/obliteration/files/13538070/dump-auth.zip)

@VocalFan this one?

**Comment by VocalFan** [comment]
Yep, another one you can do is...

CUSA01810, Tom Clancy's The Division

**Comment by ultimaweapon** [comment]
This version is not hard-coded the file name anymore. You need to create `dump-list.txt` on the root of USB drive. The format of each line in this file is:

```
PATH_TO_SELF:OUTPUT_PATH
```

Here is an example for CUSA01810:

```
/mnt/sandbox/pfsmnt/CUSA01810-app0/eboot.bin:/mnt/usb0/auth-info.bin
```

[dump-auth.zip](https://github.com/obhq/obliteration/files/13538124/dump-auth.zip)

**Comment by VocalFan** [comment]
I'll get you those two then, and maybe some media apps like youtube.

**Comment by VocalFan** [comment]
Don't forget to update your github repo!!!

**Comment by ultimaweapon** [comment]
Seems like `sceSysmodulePreloadModuleForLibkernel` use auth info of the process (not thread) to determine how to load the libraries.

**Comment by ultimaweapon** [comment]
With #481 it does something interesting. Let's hope we are on the right track.

**Comment by SuchAFuriousDeath** [comment]
That mode sys_open is getting is extremely weird.

**Comment by SuchAFuriousDeath** [comment]
<img width="472" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/36ae0006-6081-4ea7-b0ee-88716b5a0fce">

**Comment by SuchAFuriousDeath** [comment]
This is after manual casting to u32, otherwise it panics;.

<img width="330" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/1e5be714-19b0-43d2-90d3-f9e19d7abc61">

**Comment by SuchAFuriousDeath** [comment]
Some bonus information: 
<img width="544" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/832d28e2-ca92-46a7-8574-dd749f78023f">

**Comment by SuchAFuriousDeath** [comment]
Good point, I suppose this can be closed, since we're not failing on a segfault right now
