### ISSUE TITLE
Not compiling GUI app.

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#474]
Noticing an issue with Windows compilation... Atleast for me. When I click build for Windows-Debug and Core, the GUI exe isn't compiled, but the kernel exe is.

Only work around is selecting explicitly the Obliteration.exe option in building.

**Comment by ultimaweapon** [comment]
> When I click build for Windows-Debug and Core

What build did you click?

**Comment by VocalFan** [comment]
The bottom bar, Build button. Compiles LLVM and the Kernel but... Not the UI...

**Comment by ultimaweapon** [comment]
Where do those buttons come from?

**Comment by VocalFan** [comment]
Wha?

**Comment by ultimaweapon** [comment]
Can you show the screenshot of those buttons?

**Comment by VocalFan** [comment]
cmake tools (extension) 
![image](https://github.com/obhq/obliteration/assets/45863583/b37b09d5-778f-4097-85ca-2bd9ac983383)
![image](https://github.com/obhq/obliteration/assets/45863583/300095cb-2ce4-454a-95b6-4a60330440c1)
^ Doesn't make new GUI app, but does compile LLVM and Kernel

![image](https://github.com/obhq/obliteration/assets/45863583/bd51d4ca-1f11-4ca1-b3c0-7389b5faf347)
^ Picking Obliteration.exe works however.

**Comment by ultimaweapon** [comment]
Uses the button on the status bar instead.
![Screenshot from 2023-12-02 13-54-15](https://github.com/obhq/obliteration/assets/3048307/e2f1eb57-f5b3-40ac-846f-70b684995cae)

**Comment by VocalFan** [comment]
That's... The 1st image in my prev. message?

**Comment by ultimaweapon** [comment]
Can you show logs from that button?

**Comment by ultimaweapon** [comment]
@VocalFan any updates on this?

**Comment by ultimaweapon** [comment]
I'll close this for now. Feel free to re-open it when you can provide the logs.
