### ISSUE TITLE
The Kernel Crashed.

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#48]
When trying to run Amplitude (And yes, I did a fresh install), Kyty would usually give a missing instruction error. However, when running the game, it now gives a "The kernel crashed" error before Obliteration closes entirely. It doesn't even show the Kyty error.

![image](https://user-images.githubusercontent.com/45863583/202610268-409688a5-0f9d-4c48-ba8b-1c1548ce3dd4.png)
![image](https://user-images.githubusercontent.com/45863583/202610374-f3a6e35f-f65c-4727-9a23-7d96e160fd43.png)
![image](https://user-images.githubusercontent.com/45863583/202610292-8a3f158c-b10d-480d-85fa-6b7ec497331d.png)

**Comment by ultimaweapon** [comment]
Strange. Recently changes have nothing to do with the kernel. If Rust was panic it should tell it was panic but nothing was printed.

**Comment by Mou-Ikkai** [comment]
Any possible way I can help further?

**Comment by ultimaweapon** [comment]
Are you able to build on your machine? If yes try using that build to see if this problem still happens.

**Comment by ultimaweapon** [comment]
Try this build https://github.com/ultimaweapon/obliteration/actions/runs/3514045837 to see if it works.

**Comment by Mou-Ikkai** [comment]
Latest builds have fixed the crash.

**Comment by Mou-Ikkai** [comment]
I'm saying before your github action changes. The "Honors ActiveFat" change fixed it.

**Comment by ultimaweapon** [comment]
Hornors ActiveFat does not fix this issue. The reason you see it working was because the cached object files just accidentally worked with the installed toolchain on the runner. That means sometimes it will work and sometimes it will not.

**Comment by Mou-Ikkai** [comment]
I'll investigate this :3

**Comment by ultimaweapon** [comment]
Any updates? If you can't find other reasons for this problem I will reset main branch back to my commit.

**Comment by Mou-Ikkai** [comment]
> Any updates? If you can't find other reasons for this problem I will reset main branch back to my commit.

Continued testing... Every build after that one is flawless... Checking the files, it seems like the kernel file was corrupted :<

**Comment by ultimaweapon** [comment]
You can test by building the problematic commit on your machine without any object files from the previous build (remove `build` and `src/target` directory before building). If it work that mean the problem come from the cached files as I suspected.

**Comment by Mou-Ikkai** [comment]
![image](https://user-images.githubusercontent.com/45863583/204123136-2decb688-caa8-40ec-a024-52b345ce4b0a.png)
Mrow -w-

**Comment by ultimaweapon** [comment]
This is bad. We are in the situation that we don't know what cause the problem and any changes that made this work also does not get linked to the kernel.

**Comment by ultimaweapon** [comment]
I just checked your image and found out it is exactly the same as the previous image. Are you sure it is a new image that you captured from your local build?

**Comment by Mou-Ikkai** [comment]
> I just checked your image and found out it is exactly the same as the previous image. Are you sure it is a new image that you captured from your local build?

Since I have two displays, I use ctrl+alt+printscr
Which copies the selected window.

**Comment by ultimaweapon** [comment]
I'll set up Visual Studio on my Windows to test a local build.

**Comment by ultimaweapon** [comment]
I got a bad news. Even with the latest commit the local build on my Windows also crashed. That mean there is a bug somewhere for sure. I'll investigate what wrong here.

**Comment by ultimaweapon** [comment]
Just come back from my personal things but still does not have access to my Windows machine until late December. So I'll come back to this issue once I have access to my Windows machine.

**Comment by bayedieng** [comment]
![Screenshot from 2022-12-24 10-52-00](https://user-images.githubusercontent.com/58934805/209432710-5c8b8e45-d7ca-42ba-bcb4-fc5b2b8db0a9.png)

Getting the same crash on my Pop OS 22.04 machine when attempting to install the PS Scene Quiz game package.

**Comment by ultimaweapon** [comment]
I guess you are using Intel because I suspected Rust was output AMD specific instructions. On Windows I got illegal instruction errors. Could you confirm it is also your case?

**Comment by bayedieng** [comment]
No, I have an AMD CPU. Ryzen 7 3700x

**Comment by Mou-Ikkai** [comment]
> I guess you are using Intel because I suspected Rust was output AMD specific instructions. On Windows I got illegal instruction errors. Could you confirm it is also your case?

Plus I use a Ryzen 9 3900X, and even with GPU, it's AMD with 5700XT

**Comment by bayedieng** [comment]
I wonder if it has to do with using older firmware versions 5.0 and below and get this error

![Screenshot from 2022-12-25 22-14-48](https://user-images.githubusercontent.com/58934805/209483208-65b2dcae-cdf9-44b0-b134-2a6c2f6ba0b7.png)

I've tried with firmware version 8.5 and get the kernel crash error. @ultimaweapon what firmware version are you using?

**Comment by ultimaweapon** [comment]
The code for loading firmware is not finished yet so it is not related. I don't have time to debug this issue yet. If you guys want to take a look try to start debugging the kernel as stated in the README to see which line caused this error.

**Comment by ultimaweapon** [comment]
Just debug the debug version on Windows and it does not crashed. With all of information we have I'm quite sure because Rust was generated and unsupported CPU instructions on release build. I'll dig down into the problematic instructions.

**Comment by Mou-Ikkai** [comment]
https://user-images.githubusercontent.com/45863583/211244229-70476875-1521-4bad-8fa8-6f56f3fac549.mp4

Got it on my laptop. (Ryzen 5 5600H and RTX 3050Ti)

**Comment by ultimaweapon** [comment]
Just found a root cause. It is because Rust was thinking `Process::load` does nothing and decided to replace the whole method with `TrapUnreachable` somehow. I'll comeback to this issue later once I finished refactoring `Process` struct to support AArch64. I hope it will fixing this issue automatically.

**Comment by Mou-Ikkai** [comment]
> Just found a root cause. It is because Rust was thinking `Process::load` does nothing and decided to replace the whole method

So it looked at the function, said "fuck it" and just replaced it with TrapUnreachable? Lol

**Comment by ultimaweapon** [comment]
I guess we are using too much unsafe code and getting hit by Rust bugs somehow.

**Comment by bayedieng** [comment]
```0: Failed to read .kernel-debug: missing field `game`.```

How do I pass in the game field to debug the kernel?

**Comment by bayedieng** [comment]
Perhaps we should be more conservative with unsafe usage going forward. Unless absolutely necessary for optimal performance?

**Comment by ultimaweapon** [comment]
Agree. We don't want to hit this kind of bug again.

**Comment by Mou-Ikkai** [comment]
> Agree. We don't want to hit this kind of bug again.

If its a bug with Rust itself, maybe report it to them?

**Comment by ultimaweapon** [comment]
The problem is I need to put some effort for reporting bug, which I'm lazy.

**Comment by VocalFan** [comment]
Fixed
