### ISSUE TITLE
Implemenent /dev/dipsw ioctl with com = 0x40048807

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#484]
Reached after skipping #482.

**Comment by SuchAFuriousDeath** [comment]
This one again seems to return a boolean value, although returning true/false seems to make no difference.

**Comment by ultimaweapon** [comment]
Where is the function for dipsw IOCTL?

**Comment by SuchAFuriousDeath** [comment]
<img width="558" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/6b028252-1354-4a2b-8571-59a9c18c28d9">

**Comment by red-prig** [comment]
![dfgdfgdfg](https://github.com/obhq/obliteration/assets/68122101/1c8c40eb-adda-4db7-b21f-78d675f8e45f)

**Comment by SuchAFuriousDeath** [comment]
By the way, the two functions that are used here and with dipsw com6 copy 16 bytes out of some static variable. That same variable is copied out of in sysctl.machdep.hwfeature_for_decid and sysctl.machdep.idps.

**Comment by ultimaweapon** [comment]
@SuchAFuriousDeath do you remembered who are working on this one?
