### ISSUE TITLE
Find a correct auth info for game

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#494]
@ultimaweapon Your new version that reads the list doesn't work... It does return an error if the list file is missing, but if I include the list file, we get the infamous no notification or activity, and if I run the payload again, Orbis' GUI crashes... Which means the 1st payload crashed.

**Comment by VocalFan** [comment]
Ultima, I really would appreciate if you sent your code XD. Trying to modify it to be more verbose and well, your outdated code can't handle bin files.

**Comment by VocalFan** [comment]
@ultimaweapon While you're here XD

**Comment by ultimaweapon** [comment]
Today it is Thailand holiday. Here https://github.com/obhq/auth-dumper

**Comment by VocalFan** [comment]
Just looked it up and it seems to be a birthday for a king... Happy birthday, Bhumibol

**Comment by VocalFan** [comment]
Hey, I reworked some of the C code, and instead of just crashing...

![image](https://github.com/obhq/obliteration/assets/45863583/5f5d0f10-c1c7-421f-bb5b-a09326f18ff9)

**Comment by VocalFan** [comment]
```c
int _main(struct thread *td) {
    int fd, write_result;
    struct stat st;
    char *buf, *next;
    size_t i;
    struct get_auth_req req;

    initKernel();
    initLibc();
    jailbreak();
    mmap_patch();
    initSysUtil();

    // open list file
    fd = open("/mnt/usb0/dump-list.txt", O_RDONLY, 0);
    if (fd < 0) {
        printf_notification("Cannot open dump-list.txt on the USB drive.");
        return 0;
    }

    if (fstat(fd, &st) < 0) {
        printf_notification("Cannot determine the size of dump-list.txt on the USB drive.");
        close(fd);
        return 0;
    }

    // read list file
    buf = malloc(st.st_size + 1);
    if (!buf) {
        printf_notification("Failed to allocate memory.");
        close(fd);
        return 0;
    }

    i = 0;
    while (i < (size_t)st.st_size) {
        ssize_t n = read(fd, buf + i, st.st_size - i);
        if (n < 0) {
            printf_notification("Cannot read dump-list.txt on the USB drive.");
            free(buf);
            close(fd);
            return 0;
        } else if (n == 0) {
            break;
        }
        i += n;
    }

    buf[st.st_size] = '\0';
    close(fd);

    // parse list file
    next = buf;
    for (;;) {
        char *p;

        if (!*next) {
            break;
        }

        p = strchr(next, ':');
        if (!p) {
            printf_notification("dump-list.txt on the USB drive has invalid format.");
            free(buf);
            return 0;
        }
        *p = '\0';

        req.file = next;
        if (kexec(get_auth, &req) < 0) {
            printf_notification("Failed to dump auth info for %s.", next);
            free(buf);
            return 0;
        }

        next = p + 1;
        p = strchr(next, '\n');
        if (p) {
            if (p > next && p[-1] == '\r') {
                p[-1] = '\0';
            }
            *p = '\0';
        }

        fd = open(next, O_WRONLY | O_CREAT | O_TRUNC, 0777);
        if (fd < 0) {
            printf_notification("Cannot create %s.", next);
            free(buf);
            return 0;
        }

        write_result = write(fd, req.buf, 136);
        if (write_result < 0 || write_result != 136) {
            printf_notification("Failed to write auth info.");
            close(fd);
            free(buf);
            return 0;
        }
        close(fd);

        if (!p) { // if there's no newline, end the loop
            break;
        }

        next = p + 1;
    }

    free(buf);
    printf_notification("Auth info dump complete!");

    return 0;
}
```

Replace your main with this one to achieve this error.

**Comment by ultimaweapon** [comment]
Does this work https://github.com/obhq/obliteration/issues/473#issuecomment-1837367609?

**Comment by VocalFan** [comment]
From what I could tell? Nope.

**Comment by ultimaweapon** [comment]
I have no idea what wrong here.

**Comment by VocalFan** [comment]
I mean, we must have some bug or wrong implementation somewhere... I mean, we had a bug before, and this refactoring made it so we don't crash reading from the USB file...

**Comment by VocalFan** [comment]
Ah... I think it's the exact same issue I had when dumping the fPKG's authinfo, just it errors on accessing USB or somewhere else... Which I don't have after this refactor.

**Comment by ultimaweapon** [comment]
How did you get the first one for fPGK working?

**Comment by VocalFan** [comment]
> How did you get the first one for fPGK working?

Either it's because I ran the payload in /data/payloads instead of /mnt/usb0/payloads, or a chance of RNG, can't say for sure, but me putting it in /data/payloads via FTP is what made it work.

**Comment by ultimaweapon** [comment]
Have you try your version by reading and writing files in `/data/payloads`?

**Comment by VocalFan** [comment]
I'll try this when I get home:

Use USB for reading list and writing authinfo, payload on PS4 HDD

Use HDD for reading list and writing authinfo, payload on PS4 HDD

**Comment by VocalFan** [comment]
Yeah, chief, it just doesn't want to work.

**Comment by ultimaweapon** [comment]
I suspect it is caused by fSELF supports. Does your jailbreak persistent across reboot? Or you need to reactivate it again?

**Comment by VocalFan** [comment]
Jailbreak lasts on suspend, but full shutdown will remove the jailbreak until I reexecute it.

**Comment by VocalFan** [comment]
@ultimaweapon How did you show the error code for the function before when we were testing way back?

**Comment by VocalFan** [comment]
@ultimaweapon I THINK I GOT IT

**Comment by VocalFan** [comment]
If a game has a patch, you don't use -app0 to get the authinfo, you use app0-patch0-union.

**Comment by VocalFan** [comment]
```
08 44 C2 AC 03 00 00 34 00 00 00 00 80 03 00 20
00 FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 40 00 40 00 40
00 00 00 00 00 00 00 40 02 00 00 00 00 00 80 00
00 40 FF FF 00 00 00 F0 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
```

HERE WE ARE BOYS

**Comment by VocalFan** [comment]
Okay, in general, you use the app0-patch0-union, even if a game has no update, the PS4 seems to use this folder.

**Comment by VocalFan** [comment]
Saying this as Tom Clancy The Division is on 1.00, yet it has this folder.

**Comment by VocalFan** [comment]
Tried Watch Dogs 2, and exact same thing, all but the 1st 2 bytes are the same.

Diff:
`08 44` | `12 07` | `6B 11`

**Comment by ultimaweapon** [comment]
Strange. Why PAID is not `0x3800000000000011`.

**Comment by VocalFan** [comment]
> Member

It's correct though, I checked on the Auth Info from the Dev wiki, their old auth info grabs for Youtube and Twitch have this exact same info.

**Comment by VocalFan** [comment]
> I wonder where this one came from: https://github.com/flatz/pkg_pfs_tool/blob/main/src/self.h#L36

Uh, I think it's the default SELF for OpenOrbis/fPKG eboots.

**Comment by ultimaweapon** [comment]
Nope, fSELF is the top one.

**Comment by ultimaweapon** [comment]
> Tried Watch Dogs 2, and exact same thing, all but the 1st 2 bytes are the same.
> 
> Diff: `08 44` | `12 07` | `6B 11`

Those two bytes are the title ID, which is great because we can generate the correct one for each game.

**Comment by VocalFan** [comment]
Also please check my PR in auth-dumper when ya can

**Comment by ultimaweapon** [comment]
https://github.com/obhq/obliteration/commit/f63bec0dc32d83be42c4f7a0f82b6b5f70d96e8a
