### ISSUE TITLE
Implement syscall 586

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#497]
Required by CUSA13434.

**Comment by ultimaweapon** [comment]
@SuchAFuriousDeath have you seen this one or already started working on this?

**Comment by SuchAFuriousDeath** [comment]
To my knowledge, no. But they might after retesting with our new PRs.

**Comment by SuchAFuriousDeath** [comment]
This is a really good choice btw, it look even simpler than Sonic Mania.

**Comment by ultimaweapon** [comment]
It also cheap. Can't remember how much I bough this one. Maybe something like $10.

**Comment by SuchAFuriousDeath** [comment]
By the way, all the Discord games tested so far reach #485 or #482 (or trc_mem, but those will get retested soon)
