### ISSUE TITLE
Implement dmem ioctl

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#503]
Reached after #500

**Comment by SuchAFuriousDeath** [comment]
I found a function that uses the the value 0x20007461 (the com value when the console ioctl is called, which we currently skip) in a cmp instruction, maybe it could be useful. You can find it like this:
<img width="927" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/1b7f1121-eda2-4da8-86db-3e3fb2cad07d">
Maybe it's relevant for something. That is, if you hadn't found it yourself already.

**Comment by ultimaweapon** [comment]
Nice.
