### ISSUE TITLE
Implement console ioctl with com = 0x20007461

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#525]
Now that we know what it is, it should be fairly easy.

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon Actually, do we really need to implement this? Probably not, right?

**Comment by ultimaweapon** [comment]
We should implement everything that we can.

**Comment by SuchAFuriousDeath** [comment]
Right. But currently this just mutates some sort of an internal state and then nothing touches that state again (at least yet). So right now, implementing this doesn't help us at all.

**Comment by ultimaweapon** [comment]
If there are other things we can do and it has more priority than this one then do that one first.

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon Now that we know what console is... maybe we should create a separate window with a terminal for it?

**Comment by ultimaweapon** [comment]
If you are willing to work with Qt.

**Comment by SuchAFuriousDeath** [comment]
Maybe later :D

**Comment by SuchAFuriousDeath** [comment]
And what if just the kernel were running?

**Comment by ultimaweapon** [comment]
It's just a normal stderr.

**Comment by SuchAFuriousDeath** [comment]
By the way, wouldn't it be better to create sort of a wrapper type for all the strings that are actually arrays in FreeBSD? We could use const generics. It would be faster and more explicit.

**Comment by ultimaweapon** [comment]
Good idea. I think there should be a crate for this so better to check first.

**Comment by SuchAFuriousDeath** [comment]
I found arraystring, but the documentation says that it's not using const generics.

**Comment by ultimaweapon** [comment]
Seems like we need to implement this by our self.

**Comment by SuchAFuriousDeath** [comment]
By the way, after syscall 602, what's the game doing for you? The same as before? Mine is doing this:
<img width="617" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/4c9b3dab-0d80-4f27-a622-dc4293c5f36a">

**Comment by ultimaweapon** [comment]
That is an expected behavior.

**Comment by SuchAFuriousDeath** [comment]
I thought so, just making sure

**Comment by SuchAFuriousDeath** [comment]
By the way, is there a reason or threads don't have a proc field?

**Comment by ultimaweapon** [comment]
Because we only have one proc so no point to put it there.

**Comment by SuchAFuriousDeath** [comment]
The reason I'm asking is that passing a &Arc<VProc> to Dmem1 felt really weird

**Comment by SuchAFuriousDeath** [comment]
Superseded by #795
