### ISSUE TITLE
Memory Available become 0

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#545]
```
Memory Available    : 0/0 MB
```

**Comment by SuchAFuriousDeath** [comment]
I confirm that it happens for me too.

**Comment by SuchAFuriousDeath** [comment]
I think we had a sysinfo update recently and that's what causes it. Maybe we noticed just now

**Comment by StevenMiller123** [comment]
This shows up for me on Windows 11.
![Screenshot 2024-01-01 115655](https://github.com/obhq/obliteration/assets/56742918/dd9bbb03-8965-4533-8d3b-b079ada1f113)

**Comment by yegetshalaay** [comment]
Can confirm that it happens on Arch Linux too. Providing some useful? information below.

```
OS: Arch Linux x86_64
Host: B450M K (-CF)
Kernel: 6.6.10-zen1-1-zen
DE: KDE Plasma 5.27.10
Display (HP L1908w): 1440x900 @ 60Hz
CPU: AMD Ryzen 5 1600 (12) @ 3,20 GHz
GPU: AMD Radeon RX 580
Memory: 3,92 GiB / 15,54 GiB (25%)
Swap: 2,96 GiB / 48,00 GiB (6%)
Disk (/): 390,27 GiB / 397,63 GiB (98%) - f2fs
```

**Comment by VocalFan** [comment]
I'll double check this when I get home
