### ISSUE TITLE
Build: Fails when there is a space in the path

### ISSUE THREAD

**Issue by shinra-electric** [obhq/obliteration#550]
Building fails on an M1 Mac when there is a space in the path. 

The directory I'm building in is `/Applications/Games/Emulators/Playstation 4/obliteration`. You can see from the excerpts below that the path is getting split between `/Applications/Games/Emulators/Playstation` and `4/obliteration` 

It builds successfully when I change the name of the folder to `Playstation4`

```
   Compiling pfs v0.1.0 (/Applications/Games/Emulators/Playstation 4/obliteration/src/pfs)
The following warnings were emitted during compilation:

warning: clang: error: no such file or directory: '4/obliteration/lib/llvm/include'

error: failed to run custom build command for `llvm-sys v170.0.1`
```

```
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I/Applications/Games/Emulators/Playstation" "4/obliteration/lib/llvm/include" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-o" "/Applications/Games/Emulators/Playstation 4/obliteration/src/target/release/build/llvm-sys-dab67cb73b2d00cc/out/wrappers/target.o" "-c" "wrappers/target.c"
  cargo:warning=clang: error: no such file or directory: '4/obliteration/lib/llvm/include'

  exit status: 1

  --- stderr


  error occurred: Command env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I/Applications/Games/Emulators/Playstation" "4/obliteration/lib/llvm/include" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-o" "/Applications/Games/Emulators/Playstation 4/obliteration/src/target/release/build/llvm-sys-dab67cb73b2d00cc/out/wrappers/target.o" "-c" "wrappers/target.c" with args "cc" did not execute successfully (status code exit status: 1).
```

I don't know if pfs v0.1.0 is the culprit, but there have been many releases of pfs. (It's up to v0.7.0 now).

Full log is here: 
[Obliteration Output.txt](https://github.com/obhq/obliteration/files/13806418/Obliteration.Output.txt)

**Comment by ultimaweapon** [comment]
Actually it is a bug of [llvm-sys](https://gitlab.com/taricorp/llvm-sys.rs/-/issues/43). We may need to find an alternative solution for this.

**Comment by ultimaweapon** [comment]
@shinra-electric could you try the following methods?

1. Install `llvm@17` from Brew.
2. Set environment variable `LLVM_SYS_170_PREFIX` to the prefix of LLVM installation.
3. Run `cmake -DOB_BUILD_LLVM:BOOL=OFF --preset PRESET .` instead of `cmake --preset PRESET .`.
4. Build as usual.

**Comment by shinra-electric** [comment]
Skipping the llvm compile not only fixes the issue, but compilation is now much faster. 

Building still failed for an unrelated reason (type mismatch), but I'll open a separate issue for that.

For reference, these are the steps I used: 
```
# Install dependancies 
brew install qt@6 cmake rust llvm@17

# Download repository
git clone https://github.com/obhq/obliteration
cd obliteration

# Set variables
export LLVM_SYS_170_PREFIX=$(brew --prefix)/opt/llvm

# Configure build system
cmake -DOB_BUILD_LLVM:BOOL=OFF --preset mac-release .

# Amount of available cores:
CORES=$(sysctl -n hw.ncpu)

# Build
cmake --build build -j${CORES}
```
