### ISSUE TITLE
Implement nullfs

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#551]
So we can mount the directories to sandboxed app.

**Comment by SuchAFuriousDeath** [comment]
null_mount is supposed to create a vnode, but that requires an &Arc<Mount>, but the mounts functions only receives a &mut Mount. I'm not quite sure about how to best deal with this.

**Comment by ultimaweapon** [comment]
My idea is adding a new `FsOps` something like `init` and call it after the mount was added to `Mounts`.

**Comment by SuchAFuriousDeath** [comment]
Would the init function be called with mount opts? 
By the way, you can look at what I currently have at https://github.com/obhq/obliteration/pull/554. It currently doesn't compile because of what I mentioned.

**Comment by SuchAFuriousDeath** [comment]
Maybe ... mount we could create Arc<Mount>, pass it to the init function and then push it to the vec. It's not as nice, but I feel like if we created an init function, it would basically become the mount function (At least in the case of nullfs)

**Comment by SuchAFuriousDeath** [comment]
Also, how do these conditions translate to our code? 

<img width="555" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/33b4eea3-3792-4f96-a03f-5e384728a341">
<img width="524" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/41798afc-0916-4629-a066-e463a55de054">

**Comment by ultimaweapon** [comment]
> it would basically become the mount function
Not actually. The reason I would like to keep the current `mount` is because it has mutable access to `Mount`, which can do something that the other ops cannot do. It is also represent a contract that `mount` has exclusive access to `Mount`.

**Comment by SuchAFuriousDeath** [comment]
So, would the init function take mount options? I feel like it would have to.

**Comment by ultimaweapon** [comment]
Correct, it will take `&Arc<Mount>` instead of `&mut Mount`.

**Comment by ultimaweapon** [comment]
> Also, how do these conditions translate to our code?
> <img alt="image" width="555" src="https://private-user-images.githubusercontent.com/48620541/296444487-33b4eea3-3792-4f96-a03f-5e384728a341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNDA5NjEsIm5iZiI6MTcwNTE0MDY2MSwicGF0aCI6Ii80ODYyMDU0MS8yOTY0NDQ0ODctMzNiNGVlYTMtMzc5Mi00Zjk2LWEwM2YtNWUzODQ3MjhhMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDEwMTEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZmYyNTFiMDg0OGM0OWVmMzY4MzIzM2YwZDg2NGRjODdmNDk4YjNkYjZhNGI1OWZkNjhmMWZjMDE5MTg2ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FQCOs2Zusre-PBsVCx5yVqx0NkTqe--0b_exbp2mRr0"> <img alt="image" width="524" src="https://private-user-images.githubusercontent.com/48620541/296444519-41798afc-0916-4629-a066-e463a55de054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNDA5NjEsIm5iZiI6MTcwNTE0MDY2MSwicGF0aCI6Ii80ODYyMDU0MS8yOTY0NDQ1MTktNDE3OThhZmMtMDkxNi00NjI5LWEwNjYtZTQ2M2E1NWRlMDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDEwMTEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YTQ1ZTIyOGNkZWFhNmZlZWFiYjY5MDAxNmZiMjFiYTc4OTU2Y2JjNjA0YTNkYjMwMTJmOWI0MzE3MTI2ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NHuBML9o7AmJQAti05Oi76raOq1A1XaTiwrjFHSCF3g">

We don't support all of those flags and operations because... it is depend on `namei` implementation, which I decided to not implement it because the reason I stated in the `Fs::lookup()`.

**Comment by SuchAFuriousDeath** [comment]
We could also make the mount function return an Arc<Mount> instead of () and pass Mounts to it. Each mount function would then push the mount into mount and return the resulting Arc<Mount>. it would be a little bit of code duplication, but it may be worth it.

**Comment by ultimaweapon** [comment]
> We could also make the mount function return an Arc<Mount> instead of () and pass Mounts to it. Each mount function would then push the mount into mounts and return the resulting Arc<Mount>. it would be a little bit of code duplication, but it may be worth it.

The problem is people might creating an `Arc<Mount>` by `Arc::new()` instead.

**Comment by SuchAFuriousDeath** [comment]
> > We could also make the mount function return an Arc instead of () and pass Mounts to it. Each mount function would then push the mount into mounts and return the resulting Arc. it would be a little bit of code duplication, but it may be worth it.
> 
> The problem is people might creating an `Arc<Mount>` by `Arc::new()` instead.

In theory, yes, but is that really such a big deal? It's not like there's 900 filesystems to keep track of and so far it's just the two of us.

**Comment by SuchAFuriousDeath** [comment]
If we created in init function taking an &Arc<Mount> and it failed, we would have to pop the mount back from Mounts, which is... weird.

**Comment by SuchAFuriousDeath** [comment]
Also, I assume that EJUSTRETURN can't happen for us? 
<img width="503" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/e6b32ed9-7984-440c-8e6c-a533ea7b01cd">
Seems that FreeBSD can return an error value but still return a vnode.

http://fxr.watson.org/fxr/source/fs/nullfs/null_vnops.c?v=FREEBSD-9-STABLE#L358

**Comment by ultimaweapon** [comment]
> it's just the two of us.

For now. In the future we will have more people. If someone implement this and got reviewed by the other people that is not 2 of us, those people might not aware that they can't use `Arc::new`.

> It could also be prevented by requiring to return a wrapper type around Arc<Mount> that can only be obtained from Mounts::push.

I'm okay with this. The point is we should try to prevent implementation mistake by utilize Rust features.

> Also, if we created an init function taking an &Arc and it failed, we would have to pop the mount back from Mounts, which is... weird.

I agree. But if no other solutions are available this one better than allowing the people to make the mistake when implementing the FS.

**Comment by ultimaweapon** [comment]
> EJUSTRETURN

Correct. We don't support `EJUSTRETURN`. It just... kind of hack that FreeBSD dev don't know a better solution.

**Comment by SuchAFuriousDeath** [comment]
Ok, so... the wrapper type approach actually isn't so easy. But the init function wouldn't help, I think.

https://github.com/obhq/obliteration/pull/554/files#diff-a065bc8307f8be3b47731a0962b2d9efdd0c938cdd8c8d368460ac3d52c0a19eR127-R149

At line 127, we require an  &Arc<Mount>, but at line 149, we require a mutable reference to a mount

**Comment by ultimaweapon** [comment]
You can move all of vnode related operations to `init`. `mount` should not do anything with vnode.

**Comment by SuchAFuriousDeath** [comment]
Well... almost everything in the function depends on each other. mnt.set_data require data, the data is a null_mount, the null_mount is obtained from a vnode that is looked up with Fs::lookup

**Comment by ultimaweapon** [comment]
Does that mean you need `Fs`, not `init`?

**Comment by SuchAFuriousDeath** [comment]
Sure, but that's not the issue. The issue is that that if I were to move all 'vnode related operations' to init, we would require a mutable reference there. I suppose that technically

**Comment by ultimaweapon** [comment]
Wait, it seems like all you need is vnode from `Fs::lookup()`, not vnode from nullfs.

**Comment by SuchAFuriousDeath** [comment]
I... don't see how that relates the rest of this

**Comment by ultimaweapon** [comment]
From what I saw you the only vnode you need to construct for nullfs is a [root vnode](https://github.com/freebsd/freebsd-src/blob/release/9.1.0/sys/fs/nullfs/null_vfsops.c#L175), which can be defer to `root`.

**Comment by SuchAFuriousDeath** [comment]
Oh.
