### ISSUE TITLE
Github/Discord webhook

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#590]
Hey, Ultima! I need to add a webhook to this github repo that way I can automatically have the Discord server receive a notification that a new change has been merged onto the repo.

Specifically, I'll be using the push event.

**Comment by ultimaweapon** [comment]
I need the following information:

- URL of the Discord to receive the hook events.
- Content type the URL supported (`application/json` or `application/x-www-form-urlencoded`).

Send those information to my email if the URL required a secret.

**Comment by VocalFan** [comment]
Sent in email

**Comment by ultimaweapon** [comment]
```
{"message": "Cannot send an empty message", "code": 50006}
```

**Comment by VocalFan** [comment]
Still, we'll uh, see if it works.

**Comment by VocalFan** [comment]
WAIT @ultimaweapon put /github at the end of the webhook url

**Comment by VocalFan** [comment]
@ultimaweapon 
![image](https://github.com/obhq/obliteration/assets/45863583/27825f34-3db0-4ae9-9cb7-0928921aeaf4)
