### ISSUE TITLE
Implement sys_ipmimgr_call

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#626]

**Comment by mikusp** [comment]
I've started reversing that call already - I'm not sure to what extent it's used by commercial software, so I'll start with what's used by libSceNpManager's .init

**Comment by SuchAFuriousDeath** [comment]
By the way, just in case it's not obvious, you don't have to implement it fully, just the branches that are actually ran, we do it like that in a lot of places already.

**Comment by mikusp** [comment]
I know, even that is a lot of code 🥲

**Comment by SuchAFuriousDeath** [comment]
Does the branch that's ran actually return something?

**Comment by mikusp** [comment]
Looks like that is the case, they seem to expect some kind of resources to be returned, in addition to returning success from the call itself. I've stubbed like 4-5 commands and it seemed to progress further (then stuck on kern.sdk_version sysctl).

**Comment by SuchAFuriousDeath** [comment]
<img width="951" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/0212ee80-f7d2-4771-b3aa-f96724235eb8">
