### ISSUE TITLE
Support Qt lower than 6.5

### ISSUE THREAD

**Issue by perdo-nober-rs** [obhq/obliteration#675]
Hello I am love PS4 emulation and want try obliteration however i am on old mac. My mac don't supporr Big Sur Macos I'm stuck on siera. Siera is only supported up to qt 6.2

Would be good if used qt 6.2 instead of 6.5 for eventual my macos support thank you.

**Comment by ultimaweapon** [comment]
Now we are being transition from Qt to Slint so this no longer applicable.
