### ISSUE TITLE
Remove hard-coded CMAKE_PREFIX_PATH for Qt on Windows

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#69]
The reason is because the installation path might be differ for other people.

It is introduced by this commit https://github.com/obhq/obliteration/commit/24bc7275bdfd11e75a8140ded7321c524aada608

**Comment by Mou-Ikkai** [comment]
It's supposed to be a placeholder. It's the latest 6.2 version, with it also being the default install folder. It also allows the user to just paste in the CMAKE_PREFIX_PATH path.

**Comment by ultimaweapon** [comment]
Actually the user can set this variable on their own computer like I stated in the README.

**Comment by Mou-Ikkai** [comment]
> Actually the user can set this variable on their own computer like I stated in the README.

*Doesn't work for me for some reason .w.

**Comment by ultimaweapon** [comment]
I see. I'll update the instruction to specify how to set this environment variable correctly.
