### ISSUE TITLE
Find a solution for adding entitlements on macOS without buying a certificate from Apple

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#706]
We are going to need `com.apple.security.hypervisor` soon.

**Comment by VocalFan** [comment]
Self-signed cert with an automatic certification signing on build?

**Comment by ultimaweapon** [comment]
The problem with self signed is I'm not sure it will work on the user machine without installing the certificate.

**Comment by shinra-electric** [comment]
You could check how Ryujinx does it. They use the hypervisor on macOS.

**Comment by ultimaweapon** [comment]
Thanks!

**Comment by ultimaweapon** [comment]
Not sure how they get the certificate: https://github.com/Ryujinx/Ryujinx/blob/master/distribution/macos/create_macos_build_ava.sh

**Comment by ultimaweapon** [comment]
Seems like it is required to buy a certificate from Apple.

**Comment by shinra-electric** [comment]
I don’t think so. As far as I’m aware the only thing that requires a paid dev account is notarisation, which is not necessary for distribution. 

I’m sure the Ryujinx team will answer specifics on the discord channel.

**Comment by VocalFan** [comment]
@ultimaweapon From the Ryujinx team:

```
there is no certificate
it's an ad-hoc signature

you aren't forced to sign via Apple on macOS
some entitlements require an apple certificate and account
but not hypervisor and jit
```

**Comment by ultimaweapon** [comment]
Thanks!
