### ISSUE TITLE
Add AArch64 Support to Recompiler 

### ISSUE THREAD

**Issue by bayedieng** [obhq/obliteration#73]
Currently Obliteration's recompiler only provides support for x86_64 platforms. In order to support m1 macs and perhaps even Linux ARM/Android devices aarch64 will be required.

**Comment by yisonPylkita** [comment]
After building with
```bash
cmake --preset mac-debug .
cmake --build --preset mac-release
```
I'm stuck on this

```
error[E0570]: `"sysv64"` is not a supported ABI for the current target
  --> kernel/src/process/mod.rs:79:5
   |
79 |     extern "sysv64" fn exit() {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0570]: `"sysv64"` is not a supported ABI for the current target
  --> kernel/src/process/mod.rs:83:5
   |
83 |     extern "sysv64" fn handle_ud2(&mut self, addr: usize) -> ! {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0570`.
error: could not compile `kernel` due to 2 previous errors
make[2]: *** [src/core-prefix/src/core-stamp/core-build] Error 101
make[1]: *** [src/CMakeFiles/core.dir/all] Error 2
make: *** [all] Error 2
```

There are 2 ways around this
1) Implement x86_64 -> aarch64 recompiler
2) Compile this as MacOS Intel binary and let Rosetta 2 do the job

While second option is more of a hack around original problem I wonder if amount of additional work required to provide proper x86 -> aarch64 translation will be worth it. Mind you that `dynarmic` only supports x86_64 -> ARM translations. You would have to either write it yourself or try to use [Fex](https://github.com/FEX-Emu/FEX)/[Box64](https://github.com/ptitSeb/box64)

**Comment by bayedieng** [comment]
We only have support Intel mac atm, this issue is for adding general support to aarch64 devices. While it is possible to use Rosetta 2 for binary translation, we are looking to generally support any aarch64 device that fits the requirements. Dynarmic is an option but it is written in C++, although bindings could be provided it is usually quite difficult to do so with C++.  @ultimaweapon any thoughts?

**Comment by bayedieng** [comment]
Dynarmic should be more powerful in theory as it solely focuses and recompilation and performance between x86 and ARM whereas, Unicorn emulates CPU; albeit using JIT compilation and Qemu under the hood, so it should be relatively performant. Found this short thread on Hacker news to be interesting.

https://news.ycombinator.com/item?id=18302424

**Comment by ultimaweapon** [comment]
I take a look on `Dynarmic` and it seem like what it does is transform ARM to x86, not x86 to ARM. Did I missed something?

**Comment by bayedieng** [comment]
You might be right actually, I saw that it supported an ARM64 host and thought it also took x86 as input but it might just be ARM to ARM recompilation.

**Comment by bayedieng** [comment]
Btw, inside the Recompiler struct in the recompile function there is a match on the PS4's game instructions to translate them to the instructions applicable to the Target OS. Are we matching every single PS4 instruction or just the ones that may not compile. This is including the '''preserve''' function.

**Comment by ultimaweapon** [comment]
> Because if the case is we are matching every single instruction coming from the game it might be cleaner to just translate to aarch64 ourselves.

Yes we need to translate every instructions that the game is using. For some instructions we need to translate it to call our Rust function instead (e.g. `syscall`).

**Comment by bayedieng** [comment]
Then I think we should do the translation ourselves. After your done refactoring the recompiler to support translation to aarch64, I could get it to parity with the current match instructions as their currently aren't that much. After that it's just incrementally adding more instructions.

**Comment by yisonPylkita** [comment]
I've been looking at this and I found these 3rd party x86_64 -> aarch64 recompilers that are MIT licensed:
- https://github.com/FEX-Emu/FEX/tree/main/External/FEXCore
- https://github.com/Linaro/vixl/blob/main/doc/aarch64/getting-started-aarch64.md (FEX used it before, now they're focusing on their own implementation to squeeze more performance)
- https://github.com/ptitSeb/box64/tree/main/src/dynarec

(Actually there are more of them on the internet but I only included those that were primary designed to run/emulate high performance games)

There seems to be quite a lot of work required to create such recompilers from scratch, and even more work to do this with an acceptable performance. As a side note: x86_64 and aarch64 architectures have different memory models and instructions atomic on x86_64 will result in race conditions on aarch64 and placing memory barriers everywhere will kill performance.

While we're at recompilers - why there is a x86_64 -> x86_x64 recompiler in Obliteration? At first glance it doesn't make any sense.  People with Intel/AMD processors could just run an original PS4 code extracted from game ELF

**Comment by VocalFan** [comment]
> @yisonPylkita 
> While we're at recompilers - why there is a x86_64 -> x86_x64 recompiler in Obliteration? At first glance it doesn't make any sense. People with Intel/AMD processors could just run an original PS4 code extracted from game ELF

Here, let me copy and paste from the DEV chat what Ultimaweapon said:

```
Yes, the input is x86-64 instructions and the output will be the target CPU.
The real purpose is not optimization. The reason we need this even the target CPU is x86-64 is because there are some instructions that we cannot execute on non-PS4 OS.
So we want to transform those instructions.
On x86-64 it is quite easy because we don't need to transform most instructions but on AArch64 it is going to be a tough task.
Because you need to transform from one ISA to another ISA for every instructions.
```

**Comment by yisonPylkita** [comment]
> because there are some instructions that we cannot execute on non-PS4 OS

I didn't't knew it. I thought PS4 Jaguar cores are normal AMD x86_64 cores. Do you have any manual/website with these unique instructions?

**Comment by ultimaweapon** [comment]
The example cases is the value of `gs` register, which point to a different structure on each OS. Another one is `syscall` which is using to invoke the OS kernel routines. In terms of CPU instructions it is exactly the same as PC.

**Comment by bayedieng** [comment]
@yisonPylkita we've decided to go ahead and attempt use the unicorn engine in our matrix chat instead of continuing work on the recompiler. Will be creating an issue with further details.
