### ISSUE TITLE
Couldn't open systemfolder as a root directory.

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#746]
When trying to run a game, I immediately get this error:
```
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000000c38: kernel\src/main.rs:125
Starting Obliteration Kernel.
System directory    : D:\obSTORAGE\dev_sys
Game directory      : D:\obSTORAGE\dev_hdd0\CUSA04518
Debug dump directory: C:\Users\ghost\AppData\Local\OBHQ\Obliteration\kernel
Application Title   : Hatsune Miku: Project DIVA X
Application ID      : CUSA04518
Application Category: gd
Application Version : 01.00
Operating System    : Windows 11 Pro 22631
CPU Information     : AMD Ryzen 9 5900X 12-Core Processor            
Memory Available    : 19945/32678 MB
Pro mode            : false
++++++++++++++++++ E [00:00:00:00:198]:0x0000000000000c38: kernel\src/main.rs:629
Error while running kernel: filesystem initialization failed -> cannot mount rootfs -> cannot mount the filesystem -> couldn't open D:\obSTORAGE\dev_sys as a root directory -> The specified path is invalid. (os error 161)
```

Which this folder does exist, and was filled with the FTP wizard from my PS4:

![image](https://github.com/obhq/obliteration/assets/45863583/31b801f2-e282-4969-8c0d-15c73a1aa428)

**Comment by SuchAFuriousDeath** [comment]
As I pointed out in DMs, this seems to be caused by an incorrect conversion from &Path into UNICODE_STRING. I could fix it but it's probably best that someone with Windows does it so they can verify that it actually works.

**Comment by ultimaweapon** [comment]
> As I pointed out in DMs, this seems to be caused by an incorrect conversion from &Path into UNICODE_STRING. I could fix it but it's probably best that someone with Windows does it so they can verify that it actually works.

We have unit tests enabled in the CI. It was designed for this kind of case so you can test your code on other platforms.

**Comment by SuchAFuriousDeath** [comment]
I didn't think of that, thanks-

**Comment by VocalFan** [comment]
> > As I pointed out in DMs, this seems to be caused by an incorrect conversion from &Path into UNICODE_STRING. I could fix it but it's probably best that someone with Windows does it so they can verify that it actually works.
> 
> We have unit tests enabled in the CI. It was designed for this kind of case so you can test your code on other platforms.

To be fair, this been for like a month... Just only an actual concern for me since we're past this on Linux-

**Comment by VocalFan** [comment]
If anybody wishes to try to correct this, I'll test it.

**Comment by VocalFan** [comment]
@ultimaweapon Tried Process Monitor...

![image](https://github.com/obhq/obliteration/assets/45863583/4372f06f-4e14-4c72-8124-7188f6e7afc7)
It checks the game's param.sfo ^

![image](https://github.com/obhq/obliteration/assets/45863583/f07e5fab-6b7e-4bdd-8dec-38854a346b7a)
But never accesses the system folder.

I did check before and after the UNICODE conversion.

Before: `D:\\obSTORAGE\\dev_sys`
After: `D:\obSTORAGE\dev_sys`

So it seems like it SHOULD try the path... But just errors?

**Comment by VocalFan** [comment]
Not a permission issue, just used `fs::read_dir` to read the folder in a fresh rust project.

**Comment by VocalFan** [comment]
@ultimaweapon I figured it out. You have to append `\\??\\` to the start of the path. `\\??\\D:\obSTORAGE\dev_sys`

According to microsoft documentation:
![image](https://github.com/obhq/obliteration/assets/45863583/fd756e74-fa2b-4894-97f5-aea34d599fb1)

**Comment by ultimaweapon** [comment]
> @ultimaweapon I figured it out. You have to append `\\??\\` to the start of the path. `\\??\\D:\obSTORAGE\dev_sys`
> 
> According to microsoft documentation:
> ![image](https://github.com/obhq/obliteration/assets/45863583/fd756e74-fa2b-4894-97f5-aea34d599fb1)
> 

Nice finding.

**Comment by VocalFan** [comment]
@ultimaweapon You can probably do a much less hacky implementation, if you do, I'll test and merge.

```rs
        let mut path_str = String::from("\\??\\");
        path_str.push_str(path.as_ref().to_str().unwrap());
        let path = std::path::Path::new(&path_str);
```

Literally what I did lol

**Comment by VocalFan** [comment]
@ultimaweapon Alright, this is... Half done. We still need raw_mkdir. Which I just... Kinda gave up on doing myself.

**Comment by ultimaweapon** [comment]
That one should be a separated issue.
