### ISSUE TITLE
Mention in README that Hyper-V isn't available on Home editions of WIndows and that it has to be turned on in other versions

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#771]

**Comment by SuchAFuriousDeath** [comment]
I found this guide and it seems to work.
https://beebom.com/how-enable-hyper-v-windows-11-home/

**Comment by ultimaweapon** [comment]
I think just a Virtual Machine Platform is enough, which should be available on Home edition by default. No need to enable Hyper-V.

**Comment by ultimaweapon** [comment]
https://support.microsoft.com/en-us/windows/enable-virtualization-on-windows-11-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1

**Comment by ultimaweapon** [comment]
We should also mention that the CPU needs to support virtualization and this feature must be enabled on the BIOS.

**Comment by ultimaweapon** [comment]
@VocalFan wanna update the Wiki for the instructions to enable Virtual Machine Platform?

**Comment by VocalFan** [comment]
> @VocalFan wanna update the Wiki for the instructions to enable Virtual Machine Platform?

Maybe I'll make a Common Issues section

**Comment by VocalFan** [comment]
Should be good now!
https://github.com/obhq/obliteration/wiki/Common-Issues#couldnt-create-a-hypervisor

**Comment by ultimaweapon** [comment]
We should also put Wiki link in the README so people can find it.
