### ISSUE TITLE
Adds lifetime parameter to IoVec::{try_}from_raw_parts

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#787]
See https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_ptr for an example.

Also better to add document to the `IoVec`.

**Comment by SuchAFuriousDeath** [comment]
I don't know how to do this. The example doesn't map onto the our code.

**Comment by SuchAFuriousDeath** [comment]
By the way, don't you have the same problem with gutex guards? Maybe the VS Code is incorrect or I don't understand something, but I don't think the lifetime here should be static.

![image](https://github.com/obhq/obliteration/assets/48620541/694aa491-b54d-4130-8364-3369071411fc)

**Comment by ultimaweapon** [comment]
I turned off inlay hint.

**Comment by SuchAFuriousDeath** [comment]
Ok, but is the 'static lifetime correct, or not?

**Comment by ultimaweapon** [comment]
After taking a look we have a bigger problem than a life time of two methods here. I'll close this issue and create a new one.
