### ISSUE TITLE
Resolve the difference between our 'ModuleFlags' and fpPS4's 'rtld_flags'

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#799]
It seems like there are some differences between these two types, which I'm pretty sure correspond to each other.
![image](https://github.com/obhq/obliteration/assets/48620541/0703a171-35ec-48b1-a6cf-8f1cb90e4910)
![image](https://github.com/obhq/obliteration/assets/48620541/e04306f6-bfad-4560-a012-9b5f8c9721aa)

**Comment by red-prig** [comment]
rtld_flags are not bit-accurately copied so don't pay attention to the order of the fields in the record

**Comment by SuchAFuriousDeath** [comment]
Oh 👀

**Comment by red-prig** [comment]
```
mainprog	0x01
textrel		0x02
		0x04
tls_done	0x08
init_scanned	0x10
on_fini_list	0x20
dag_inited	0x40
		0x80
is_system	0x100
in_new		0x200
libc_fios	0x400
jmpslots_done	0x800
not_get_proc	0x1000
```
