### ISSUE TITLE
Redesign Uio and IoVec

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#817]
The problem with our current `IoVec` and `Uio` is:

- `IoVec` is constructed from a const pointer but provide a method `ptr` that return a mut pointer.
- Two copy of `Uio`, one for immutable and one for mutable.

**Comment by ultimaweapon** [comment]
This can be solve by adding a generic parameter to `Uio` to represent either mutable or immutable `IoVec`. The problem is this solution cannot be used in our case because `Uio` need to be passed to a method that is object safe.

**Comment by SuchAFuriousDeath** [comment]
I thought about generics too. But I don't quite see the problem

**Comment by SuchAFuriousDeath** [comment]
We won't be passing a generic parameter, we'll be passing a specific type, won't we?
Let's say:

```
 UioGeneric<T> {
...
}

type Uio = UioGeneric<*const u8>
type UioMut = UioGeneric<*mut u8>

and then

...
fn read(&self, uio: &mut UioMut, ...)
...

```

**Comment by SuchAFuriousDeath** [comment]
I don't really see how to fix the pointer problem. We could return a reference, but it still requires converting it into a pointer.

**Comment by ultimaweapon** [comment]
Another solution is to remove both `IoVec` and `Uio` altogether then handle `iovec` directly in the syscall that accept it. The benefits of this solution is our internal will be simpler and it work well with Rust. The problem is I'm not sure if this going cause any roadblocks in the future.

**Comment by SuchAFuriousDeath** [comment]
I'm not sure what you mean. There's at least 10 syscalls that use it.

**Comment by ultimaweapon** [comment]
I mean we for each `iovec` in the syscall directly and construct a (mutable) slice from each of it then invoke our internal method that accept a (mutable) slice.

**Comment by SuchAFuriousDeath** [comment]
Maybe that could be.

**Comment by SuchAFuriousDeath** [comment]
What about vectored reads?

**Comment by ultimaweapon** [comment]
> What about vectored reads/writes?

I totally forget there are `std::io::Read::read_vectored` and `std::io::Write::write_vectored`, which accept `IoSliceMut` and `IoSlice` that guaranteed to be ABI compatible with the `iovec`. Our next problem is: What should be do with `uio`?

**Comment by SuchAFuriousDeath** [comment]
I'm not sure.

**Comment by SuchAFuriousDeath** [comment]
By the way, This is a priority issue, Bloodborne is currently stuck on sys_read. :D

**Comment by ultimaweapon** [comment]
I'll try to rewrite this part to see if I can figure out a solution for `uio`.

**Comment by ultimaweapon** [comment]
Things will be much easier if we don't need object safety. The problem is *nix was designed with polymorphism so we have no other way.

**Comment by SuchAFuriousDeath** [comment]
Maybe uio could be just a reference to a slice of IoSlice or IoSliceMut, the offset would be passed as an argument and the number of the bytes could just be counted when it's needed, not ahead of time. Unless FreeBSD does some weird stuff with uio/uiomut, we should be fine, probably

**Comment by ultimaweapon** [comment]
I'm not satisfied with my first attempt that try to keep `uio` structure. I'll try again without it.

**Comment by SuchAFuriousDeath** [comment]
Good luck

**Comment by ultimaweapon** [comment]
Another issue we need to handle is atomicity of a list of `iovec`. I'm not sure if the PS4 and FreeBSD guarantee that any readv/writev will do atomic read/write to all passed `iovec`.

**Comment by SuchAFuriousDeath** [comment]
By the way, sys_read 'Bloodborne Alpha Test' is stuck on (someone tested that on Discord), the real Bloodborne dies on weak symbols.

**Comment by ultimaweapon** [comment]
This is going to be a big changes. It seems like I can't finish it today so probably next weekend.

**Comment by ultimaweapon** [comment]
The good news is it so far so good.
