### ISSUE TITLE
Crash upon extracting system files from the FTP server

### ISSUE THREAD

**Issue by polybiusproxy** [obhq/obliteration#864]
Obliteration, on the initial setup, will crash while trying to extract the required system files from the PS4's FTP server. This happens with both 'Explicit Decryption' enabled and disabled.

- PS4 firmware 11.00
- Using GoldHEN

**Comment by ultimaweapon** [comment]
Thanks for reporting. I'm planning to change how to dump the system files soon. I'll let you know once it is ready.

**Comment by ultimaweapon** [comment]
The new method to dump the system files https://github.com/obhq/firmware-dumper. Please note that the current version is intended to be used for development only. It is likely you will need to dump again when we release the first version.
