### ISSUE TITLE
(Question) Do you know the shadPS4 emulator?

### ISSUE THREAD

**Issue by hardBSDk** [obhq/obliteration#883]
You could it use it as reference.

https://github.com/shadps4-emu/shadPS4

**Comment by ultimaweapon** [comment]
We can't use it for two reasons:

1. We take a different approach on emulation. ShadPS4 emulates the PS4 libraries while we emulate the PS4 kernel.
2. ShadPS4 is licensed under GPL while we are licensed under MIT.
