### ISSUE TITLE
Make VMM support Intel CPU

### ISSUE THREAD

**Issue by ultimaweapon** [obhq/obliteration#905]
See https://github.com/obhq/obliteration/pull/904#issuecomment-2254501621 for the details. The problem is I don't use Intel CPU so I can't really test this. Need someone who have Intel CPU to work on this (or someone willing to be a tester).

**Comment by ultimaweapon** [comment]
@SuchAFuriousDeath I totally forgot that I have one PC with an Intel CPU so I'll take on this issue.

**Comment by ultimaweapon** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor/issues/305

**Comment by ultimaweapon** [comment]
Seems like TSS is not a culprit here because TSS address used only on real-mode: https://github.com/torvalds/linux/blob/master/arch/x86/kvm/vmx/vmx.c#L3128

**Comment by SuchAFuriousDeath** [comment]
Does running the vm give you the same error?

**Comment by ultimaweapon** [comment]
I got the same problem as you on Intel® Core™ i5-1035G4. Trying to figure out what is the problem.

**Comment by SuchAFuriousDeath** [comment]
Maybe you tried already, but the KVM_GET_VCPU_EVENTS ioctl should give some more information about what is happening.

**Comment by ultimaweapon** [comment]
It turn out Intel violate the x86-64 specs on CS.
