### ISSUE TITLE
unknown p_type 1685382480 on program header 7

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#950]
After the newest commit: 
Couldn't run /home/tompro/CLionProjects/obliteration/src/target/x86_64-unknown-none/debug/obkrnl: unknown p_type 1685382480 on program header 7.

Is this supposed to happen?

**Comment by ultimaweapon** [comment]
This is `PT_GNU_EH_FRAME`. We can ignore it since we don't use unwind panic.
